### DISCUSSION TITLE
Quoting `CONTAINER_RELEASE_URL` causes curl to fail with `URL rejected`

### DISCUSSION THREAD

**Discussion by eiredrake** [felddy/foundryvtt-docker#1040] [Q&A] [answered]
Greetings all,

I've been trying to install the foundryVTT docker with a docker-compose.yml file. Everything seems to go alright until I get a strange error within the container. Can anyone shed some light on what is going on?

Error on container start
```console
foundryVTT  | Entrypoint | 2024-08-16 04:14:30 | [info] Downloading Foundry Virtual Tabletop release.
foundryVTT  | Warning: Failed to get filetime: No such file or directory
foundryVTT  | curl: (3) URL rejected: Port number was not a decimal number between 0 and 65535
foundryVTT exited with code 3
```

my compose file looks like this
```yaml
secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    container_name: "foundryVTT"
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    volumes:
      - type: bind
        source: "D:/rpg_assets/foundry_docker/volume"
        target: "/data"
    environment:
      - CONTAINER_PRESERVE_CONFIG="true"
      - FOUNDRY_RELEASE_URL="https://r2.foundryvtt.com/releases/12.331/FoundryVTT-12.331-Setup.exe?verify=1723781642-82U%2Fos6yjcKBM70d7QmJLNVapZL5MzhOeWpVQ9lyCOs%3D"
    ports:
      - 30000:30000
    secrets:
      - source: config_json
        target: config.json
```
