### DISCUSSION TITLE
Create a share container for assets for multiple licences

### DISCUSSION THREAD

**Discussion by BenNelsonNeb** [felddy/foundryvtt-docker#1117] [Q&A]
### Feature description

Docker variables to add an optional "share" source folder on the same system for assets (not subscriptions) to be shared across multiple "share" target Foundry folders.

### Motivation

I have four instances of your wonderful docker file for each of my different GM friends. Each has different ports, and the licenses are tied to their accounts. Everything works great, but I cannot figure out how to have a shared assets folder for all of us. Is there some docker magic to create a "Share" file outside of the "Data" files (but on the same system) but appear inside the "Data" file.  I have a asset folder with maps, tokens, sound, images, overlays and its totals 10gb in size. I want to share it with the group but don't want to duplicate it 4 time.

### Example

I would like to create a folder in /home/main/foundry/data/share that links to a folder /home/main/desktop/share.  The desktop/share would contain assets.  When in the a foundry session and opening for a tile to choose look under the data/share folder and see those assets.

Variable options
CONTAINER_SHARE_SOURCE=/home/desktop/share --- Location of the assets
CONTAINER_SHARE_TARGET=/data/share --- folder location in the foundry structure that links to the source folder

### Pitch

This is a way to share assets by linking files which prevents duplication of files, saving space. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ButterCatz** [comment]
Try something like this:
```
secrets:
  config1_json:
    file: secrets1.json
  config2_json:
    file: secrets2.json

services:
  foundry1:
    image: felddy/foundryvtt:release
    container_name: fvtt1
    volumes:
      - type: bind
        source: ./data/foundry1
        target: /data
      - type: bind
        source: ./data/shared
        target: /data/Data/shared
    environment:
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config1_json
        target: config.json

  foundry2:
    image: felddy/foundryvtt:release
    container_name: fvtt2
    volumes:
      - type: bind
        source: ./data/foundry2
        target: /data
      - type: bind
        source: ./data/shared
        target: /data/Data/shared
    environment:
    ports:
      - target: 30000
        published: 30001
        protocol: tcp
    secrets:
      - source: config2_json
        target: config.json
```

I haven't tested this since I don't have two copies of fvtt, but this should create two containers with a shared directory. Puts your licenses in secret{1, 2, etc}.json respectively.
