### DISCUSSION TITLE
Environment settings from docker-compose.yml are not working

### DISCUSSION THREAD

**Discussion by OldSaltGorg** [felddy/foundryvtt-docker#1127] [General]
Hey!
Firstly, massive thanks to @felddy for making this container & guide. It finally helped me get the courage need to get my Foundry server up and running! 
I have one small issue that can't figure out though... The "environment" variables (or really any setting in the docker-compose.yml) don't seem to work or get initialised correctly. 

E.g. I want telemetry off and automatically start my world. However, neither of these things happens despite the compose file being set correctly. I did rebuild the container via Portainer when I updates the .yml file. 
In fact, docker compose setting for restart: "always" doesn't seem to work either, when I stop the container in Portainer, it doesn't start itself up automatically. 

Any thoughts of what might be going wrong?
Please help, and bear with me, I'm new to linux, docker and all of this. 😅

```
---
version: "3.8"

secrets:
  config_json:
    file: fsecrets.json

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: XXX.XX
    init: true
    restart: "always"
    volumes:
      - type: bind
        source: /home/gorg/docker/foundry
        target: /data
    environment:
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_HOSTNAME=XXXXX.XX
      - FOUNDRY_TELEMETRY=false
      - FOUNDRY_WORLD=Saitias
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json
```

These are the container logs from Portainer when I restart the foundry container: 
```FoundryVTT | 2024-12-22 14:31:21 | [info] Application Options:
{
  "awsConfig": null,
  "compressSocket": false,
  "compressStatic": false,
  "cssTheme": "foundry",
  "fullscreen": false,
  "hostname": null,
  "hotReload": false,
  "language": "en.core",
  "localHostname": null,
  "passwordSalt": null,
  "port": 30000,
  "protocol": null,
  "proxyPort": 443,
  "proxySSL": true,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "updateChannel": "stable",
  "upnp": false,
  "upnpLeaseDuration": null,
  "world": null,
  "adminPassword": "••••••••••••••••",
  "deleteNEDB": false,
  "noBackups": false,
  "serviceConfig": null
```

I do get this when I try to restart the container from Portainer GUI. So I have to start it manually again. Idk if that's related at all. 

> FoundryVTT | 2024-12-22 14:30:54 | [error] A fatal error occurred while trying to start the Foundry Virtual Tabletop server: Foundry VTT cannot start in this directory which is already locked by another process.
Error: A fatal error occurred while trying to start the Foundry Virtual Tabletop server: Foundry VTT cannot start in this directory which is already locked by another process.
    at _acquireLockFile (file:///home/foundry/resources/app/dist/init.mjs:1:5233)
    at async _initializeCriticalFunctions (file:///home/foundry/resources/app/dist/init.mjs:1:2861)
    at async Module.initialize (file:///home/foundry/resources/app/dist/init.mjs:1:1788)`
