### DISCUSSION TITLE
`v13` Breaking Changes and Fixes

### DISCUSSION THREAD

**Discussion by felddy** [felddy/foundryvtt-docker#1197] [General]
This thread will help you quickly make the changes needed to migrate from the `v12` version of this container to `v13`.  Specifically it will address the causes of the failure logged in the lines below:

```console
Entrypoint | 2025-04-19 18:35:53 | [error] Volume write test failed.
Entrypoint | 2025-04-19 18:35:53 | [error] Volume read test failed.
Entrypoint | 2025-04-19 18:35:53 | [error] Volume delete test failed.
Entrypoint | 2025-04-19 18:35:53 | [error] Aborting due to insufficient permissions on /data
Entrypoint | 2025-04-19 18:35:53 | [error] Container running as uid:gid: 1000:1000
Entrypoint | 2025-04-19 18:35:53 | [error] For more information see the discussion at: https://github.com/felddy/foundryvtt-docker/discussions/1197
```

# What Changed in v13? #
 
1. The container no longer executes as `root`.  The default `uid` and `gid` are now `1000:1000`. 
1. Since the container does not have root permissions it can no longer change the permissions in the `data` volume to match the `uid` and `gid` of the server process.  The `CONTAINER_PRESERVE_OWNER` environment variable that controlled this behavior is now deprecated.  
1. `FOUNDRY_UID` and `FOUNDRY_GID` environment variables have been deprecated in favor of the native controls for the container's runtime.  See below for more information.
1. The internal home directory has changed from `/home/foundry` to `/home/node`
1. The `TIMEZONE` environment variable has been replaced by the [standard `TZ` environment variable](https://www.gnu.org/software/libc/manual/html_node/TZ-Variable.html).
1. `linux/arm/v6` support [has been dropped](https://github.com/felddy/foundryvtt-docker/commit/cedeb515d2bb74fb4419ca715407be766fb7613f).

See the [release notes for `13.341.0`](https://github.com/felddy/foundryvtt-docker/releases/tag/v13.341.0) for additional details and changes.

# Resolving Permission Errors #

You can either:
- make the data match the default process owner, or
- make the container process ownership match the existing data

>[!TIP]
> Changing the ownership of the data is the easier of the two methods. 

## Changing the ownership of your `/data` directory ##

```bash
sudo chown -R 1000:1000 /path/to/your/data
```

>[!NOTE]
> If you've moved the `CONTAINER_CACHE` directory outside of your `data` directory
> you will need to reconcile the permissions of it as well. 

## Changing the user and group of the server process ##

>[!NOTE]
> The container previously used `uid:gid` of `421:421`.
> If you didn't set your own custom ownership with `v12` you should use `421` below. 
> If you previously set a custom `uid` and `gid` then use those same values with the new syntax.

Replace environment variables with runtime configurations.

#### Compose files ####

v12 syntax:

```yml
environment:
  - FOUNDRY_UID=421
  - FOUNDRY_GID=421
```

v13 syntax:
```yml
user: 421:421
```

#### Command line ####

v12 syntax:

```shell
...  --env FOUNDRY_UID=421 --env FOUNDRY_GROUP=421
```

v13 syntax:

```shell
... --user 421:421
```

### Kubernetes ###

v12 syntax:

```yml
env:
  - name: FOUNDRY_UID
    value: "421"
  - name: FOUNDRY_GID
    value: "421"
```

v13 syntax:

```yml
securityContext:
  runAsUser: 421
  runAsGroup: 421
  fsGroup: 421
```

---

Feel free to comment about your experience and any changes you think should be made to these instructions.

**Comment by felddy** [comment]
Link to an associated Reddit thread: https://www.reddit.com/r/FoundryVTT/comments/1kd41s1/anybody_else_struggling_to_get_version_13_up_and/

**Comment by johnpaul36** [comment]
i was using this container in unraid but now since the update its broken how do i fix the permissions

**Reply by felddy** [reply]
I don't use [Unraid](https://unraid.net), but what I can gather from the [Unraid documentation](https://docs.unraid.net/unraid-os/manual/docker-management/) these should roughly be the steps:

1. Stop the Foundry container

    - In the Unraid Web UI, go to the Docker tab, find your FoundryVTT container and click Stop.

1. Open a shell on the Unraid host

    - SSH in as root:

    ```bash
    ssh root@<your-unraid-host>
    ```

    - Or click Terminal in the Unraid Web UI (top‑right) for a root shell.

1. Locate the host path of your data share
Most likely under `/mnt/user/appdata/....` 

    ```bash
    /mnt/user/appdata/foundryvtt
    ```

1. Chown the directory recursively

    ```bash
    chown -R 1000:1000 /mnt/user/appdata/foundryvtt
    ```

1. Verify ownership

    ```bash
    ls -ln /mnt/user/appdata/foundryvtt
    ```

    You should see both owner and group set to `1000:1000`.

1. Restart the container

In the Docker tab, click Start on your FoundryVTT container.

If this isn't correct, I think you'd get more targeted help from the [Unraid Docker FAQ forum](https://forums.unraid.net/topic/57181-docker-faq/).

**Reply by johnpaul36** [reply]
thanks so much this solved my issue

**Reply by BjornEinherji** [reply]
Holy hell thanks a lot for this! I was not aware of the changes in the new version so I kept blaming myself for screwing this up and kept troubleshooting. I changed permissions in my troubleshooting, but not the correct ones i see. Man glad that is over. Thank you for keeping this updated btw.

**Reply by Nicholaiii** [reply]
For other people using Unraid, set the UID and GID to 99 and 100. This is the default Unraid settings, and recommended to stay this way.

**Comment by iamq-dev** [comment]
I am unable to run `sudo chown -R 1000:1000 /path/to/your/data`. Where is the sudo password for the container defined?

**Reply by iamq-dev** [reply]
```
 chown -R 1000:1000 ./data
chown: changing ownership of './data/Backups2/modules/dnd-dungeon-masters-guide/module.dnd-dungeon-masters-guide.2025-01-26.1737929580097.bak': Operation not permitted
chown: changing ownership of './data/Backups2/modules/dnd-dungeon-masters-guide/module.dnd-dungeon-masters-guide.2025-01-26.1737929580097.json': Operation not permitted
chown: changing ownership of './data/Backups2/modules/dnd-dungeon-masters-guide': Operation not permitted
chown: changing ownership of './data/Backups2/modules/dnd-players-handbook/module.dnd-players-handbook.2025-01-26.1737917172819.bak': Operation not permitted
...
```

```
$ sudo 
/bin/sh: 11: sudo: not found
```

```
$ su
Password: 
su: Authentication failure
```

Running on windows server. docker backend is wsl. I have tried to chown in the wsl context but am still getting permission errors. I have also attempted to use windows permissions dialogs to give permissions to `docker-users` and even `Everyone`.

**Reply by felddy** [reply]
You should perform the permission changes on the host.  The container does not have utilities for managing permissions or escalation of privileges.

**Comment by travisby** [comment]
Really appreciate the log line.  I would have spent a lot longer debugging if not for that!

**Reply by aep** [reply]
same. thank you @felddy  for the excellent work. this container is better maintained than some enterprise stuff.

**Comment by kunoichi6212** [comment]
I am hosting Foundry off my Synology. Am I able to do this using environment variables at all? If not how can I fix this so I can run 13?

**Reply by serlex00** [reply]
I'm also on synology and I'm very confused :-/

I use the second set of variables (user/password) and therefore I do not have CONTAINER_CACHE defined in my yaml.  I just the container from scratch so user: 421:421 should work but it doesn't. 

:-/

![image](https://github.com/user-attachments/assets/1ee323e8-bc93-4cc5-90c7-547e5b575c13)

**Reply by RodiakWolfshain** [reply]
Hey... I found a solution for this problem.
You need to go to your Terminal Settings in Synology and activate there "SSH"

Then, if you are working with a windows pc, use powershell and enter
`ssh <your synology username>@<your synology ip>`

you want to continue the connection and enter your password (it is not visible!)

after that, you should see something like
`<your synology username>@<whatever your synology is called> `
in green letters

enter
`sudo chown -R 1000:1000 /volume1/<your data path>`
its case sensitive, so beware. 

enter your password again, if prompted... aaaaand you should be good to go.

**Reply by shinskoll** [reply]
What if this doesn't work anymore on my Synology, my first installation did work after this workaround but I recently had to remake my foundry installation after splitting my two hdd in two volumes instead of a SHR raid1

And even triple checking if my ``/volume1/<data path>`` is effectively owned by ``1000:1000`` with ``ls -ld`` (it apparently is, if it's the correct command), the docker still refuse to launch because of inability to write/read in this data folder.
I even tried to duplicate the Docker a with an empty data folder, to no success.

What could have gone wrong?

**Reply by Whiddy** [reply]
> Hey... I found a solution for this problem. You need to go to your Terminal Settings in Synology and activate there "SSH"
> 
> Then, if you are working with a windows pc, use powershell and enter `ssh <your synology username>@<your synology ip>`
> 
> you want to continue the connection and enter your password (it is not visible!)
> 
> after that, you should see something like `<your synology username>@<whatever your synology is called> ` in green letters
> 
> enter `sudo chown -R 1000:1000 /volume1/<your data path>` its case sensitive, so beware.
> 
> enter your password again, if prompted... aaaaand you should be good to go.

It worked! Thank you very much! :)

**Reply by TheodoreBrinkman** [reply]
Also trying to get this up and running on a Synology NAS (DS223j).  Container manager no longer seems to allow editing of environment variables after initial creation of the container.  (Not even by duplicating it as described.)

I've tried the methods described both here:
#https://foundryvtt.wiki/en/setup/hosting/synology-with-docker
and here:
#https://foundryvtt.wiki/en/setup/hosting/Synology#setting-up-with-docker-no-command-line

But both leave me with the access permissions error, and the chown command above doesn't seem to resolve it.

**Reply by voltcitron** [reply]
(I'm Shinskoll from July 30, I signed on on another account by mistake)
I was able to make it work last month.
FIrst I now use docker_compose.yml written (copy/pasted mostly...) in the Container Manager to better manage editings, since as you said Theodore, it's hard to modify packages now...

And then i noticed some packages tell you to have this line `user : 1000:1000` or the like in the yml file, and so long story short I made an user with almost no access to the NAS that I use for this trend to make unusable docker otherwise, it's something like `user : 1041:100` in the yml file and then I chmod 775 + chown 1041:100 the folders.

Don't know if it's good practice or otherwise but that was the only thing that made it work.

**Reply by TheodoreBrinkman** [reply]
Where in Container Manager can you see the yml to paste something in?

I've got a distinct Docker user and group, so I understand the 1041 reference to be the user's ID, but I never saw an option to edit a config file.

**Reply by hidechron** [reply]
You have to go to "Project" in the sidebar, then "Create", then in the dropdown for "Source" select the second one.
<img width="753" height="488" alt="image" src="https://github.com/user-attachments/assets/647d1118-dca8-4638-81b8-92dc0d23c6b3" />
(the fu, how many github account do I have >_<)

**Reply by TheodoreBrinkman** [reply]
I think the chmod 775 may have been the key.  Once I did that the chown 1000:1000 worked.

**Reply by TheodoreBrinkman** [reply]
I've gotten it working thanks to the suggested chown command, but can you post a sanitized version of your .yml in case other people have issues in the future?

**Reply by voltcitron** [reply]
```---
services:
  foundry:
    image: felddy/foundryvtt:latest
    user: "1041:100"
    hostname: myhostname
    restart: on-failure
    volumes:
      - ./data:/data
    environment:
      - FOUNDRY_PASSWORD=mypass
      - FOUNDRY_USERNAME=myusername
      - FOUNDRY_ADMIN_KEY=mykey
      - CONTAINER_PRESERVE_CONFIG=true
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
```

**Reply by stetsonsdev** [reply]
So I was running into this issue as well. When you run "sudo chown -R 1000:1000 /path/to/your/data" be sure to use the specifc uid and gid in the chown command. So in my case I ran "sudo chown -R 1027:65536 /volume1/docker/foundry" then in the docker compose file include the "user:" line mentioned by voltcitron

**Comment by EvilRenegade** [comment]
@felddy I don't know how you (hard)coded those UIDs and GIDs, but on rootless Podman, the container utterly ignores all userns settings.

For others also running **rootless** Podman:
When you set up Podman, you also set up subuids and subgids for your executing user. Your volume/Foundry data should be owned by one of those subuids. **Leave it like that.**
To your previous command to run Foundry's container, add `--uidmap=1000:421:1 --uidmap 0:0:1`.
This should fix the permission mapping and allow you to start the container as before.

This works by assigning your user's intermediate uid 421 (your 421st subuid) on the host to uid 1000 in the container.
Since the container previously used uid 421 internally, this will come out to map the new container uid 1000 to the same host uid previously used in the host file system.

@felddy I acknowledge, respect and appreciate that an explanation and a link to this issue were logged by the container.
However, I would appreciate it if, next time around, instead of terminating the container in error, you could redirect to an explanatory page in the webserver, so that when the administrator tries to open Foundry, they instead get a warning and steps to fix.

Because those of us who are using your container because they're running Foundry headless on a server will have spent quite some time confusedly debugging the server before they see your message.

Not the least because you have consistently delivered a high quality product.
Your Foundry images have been running stable and reliable for years. I am very happy with them and I thank you for maintaining them.

It does mean that it's the last place I'm looking for a problem when the stack is failing, though.

If your image has always worked fine, and I just altered the stack to add a new cached installer, pull a new container image, update the process manager config to account for a new release tag, and then the container doesn't start, what is more likely: That I did everything right and your image just _chooses_ not to run...or that I fucked up along the way?
Maybe the installer has the wrong filesystem permissions.
Maybe I didn't rename the ZIP properly.
Maybe there's a typo in the process manager config.
Maybe I swapped a digit in FOUNDRY_VERSION.

There are so many things I could've done wrong accidentally, that "maybe I did everything right and Foundry just doesn't want to run" isn't going to be high on the debugging checklist.

Sure, at some point, you get to the "this doesn't make sense...this _should_ work...what does Podman say?" stage and see your message.

But adding a release notes vhost to the webserver and redirecting visitors if something's wrong gets your message to the reader a lot quicker...
Hell, you could even get fancy and just add a permanent /status endpoint, and just redirect to that on error.

Maybe something for the 13.345-version of the image? <_<

**Reply by Fraetor** [reply]
For running under rootless podman, I found that adding `userns_mode: keep-id` to my docker-compose.yml did the trick. This relies on your data directory also being owned by user 1000 on the host.

**Reply by EvilRenegade** [reply]
Not using compose, so it may be related to that.
Or to the fact that Debian doesn't like packages younger than the last ice age.

Either way, for me, uidmapping it to the previous user was what ultimately worked.

**Reply by Fraetor** [reply]
I did have to install podman-compose from `bullseye-backports` to get the feature.

**Reply by apastuszak** [reply]
How do I do this using a kubernetes yaml for Podman?

**Reply by Fraetor** [reply]
**Update:** After upgrading my host to Debian Trixie adding userns_mode failed with `Error: --userns and --pod cannot be set together`. This can be resolved by not running the containers in a pod by adding the following to your docker-compose.yaml file:

```yaml
x-podman:
    in_pod: false
```

Documentation: https://github.com/containers/podman-compose/blob/main/docs/Extensions.md#custom-pods-management

**Comment by carleberg** [comment]
A detail left out: the container cache directory (and the .zip file itself) must also have their ownership changed. Meaning `sudo chown -R 1000:1000 /path/to/your/container_cache`. 

Without it, you'll get an error saying: "CACHEDIR.TAG: permission denied". For me it was not enough to run `chown` on the data folder, I also had to do it on the folder where I store my installation .zip file. I was only able to solve this by tracking down the actual code for when this was changed: https://github.com/felddy/foundryvtt-docker/pull/1159, since the error message didn't actually tell what the error was.

**Reply by felddy** [reply]
Thank you for reporting this case.  I've added a note above mentioning this situation.

**Comment by apastuszak** [comment]
OK, I cannot get the v13 container to start. I'm running it using rootless podman, and no matter what I do, I get this in my logs:

```
Entrypoint | 2025-07-12 21:12:05 | [info] Starting felddy/foundryvtt container v13.346.0
Entrypoint | 2025-07-12 21:12:05 | [error] Volume write test failed.
Entrypoint | 2025-07-12 21:12:05 | [error] Volume read test failed.
Entrypoint | 2025-07-12 21:12:05 | [error] Aborting due to insufficient permissions on /data
Entrypoint | 2025-07-12 21:12:06 | [error] Container running as uid:gid: 421:421
Entrypoint | 2025-07-12 21:12:06 | [error] For more information see the discussion at: https://github.com/felddy/foundryvtt-docker/discussions/1197
```
I'm using a Kubernetes YAML file and running `podman play kube foundryvtt.yaml`

My yaml file is:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: Foundry_VTT
  labels:
    io.containers.autoupdate: registry
  annotations:
    # This tells Podman to create a user namespace where the host user's UID/GID
    # is mapped to UID 1000 and GID 1000 inside the container.
    io.podman.annotations.userns: "auto:uidmapping=0:0:1,uidmapping=421:1000:1"
spec:
  containers:
    - name: Foundry_VTT
      image: docker.io/felddy/foundryvtt
      env:
        - name: TZ
          value: "America/New_York"
        - name: FOUNDRY_USERNAME
          value: "XXXXXXXXXX"
        - name: FOUNDRY_PASSWORD
          value: "rEdAcTeD"
        - name: CONTAINER_PRESERVE_CONFIG
          value: "true"
        - name: FOUNDRY_ADMIN_KEY
          value: "ReDaCtEd"
      ports:
        - name: foundry
          containerPort: 30000
          hostPort: 30000
          protocol: TCP
      volumeMounts:
        - name: foundry_data
          mountPath: /data:z
  dnsPolicy: Default
  restartPolicy: Never
  SecurityContext:
    runAsUser: 421
    runAsGroup: 421
    fsGroup: 421

  volumes:
    - name: foundry_data
      hostPath:
        path: /home/andy/.podman/foundry_vtt/data
```
For the `uidmapping`, I've tried `421:1000:1` and `1000:421:1` and neither one works.

The data directory has owner:group set to 1000:1000. I'm running the pod as myself, which has a uid=1000,gid=1000

**Reply by EvilRenegade** [reply]
It's hard to determine after the fact, since you already got it working, but I believe the reason my solution didn't work for you was that you were going in the other direction:

- My solution assumes a state where the folder is owned by 421, and the container is newly running as 1000, so 1000 has to get remapped to 421.
- Your description here looks like your folder was owned by 1000, and you had reconfigured the container to run as 421. So you had a mismatch again.

The likely reason your solution from below worked is because your new config doesn't contain the security context, so now your folder owned by 1000 is getting accessed by the container newly running as 1000.
Where my solution aims to create the state described under "Changing the user and group of the server process" (data and container appearing as UID 421), you seem to have achieved the state described under "Changing the ownership of your /data directory" (data and container appearing as UID 1000).

You can check if your setup is sane by uploading something through Foundry (like a map or a token), and then checking if file ownership in the file system matches the other files.

**Comment by apastuszak** [comment]
Ok, I got it up! Here is what I did to fix it.

This is the yaml I used:

```
---
apiVersion: v1
kind: Pod
metadata:
  name: Foundry_VTT
  labels:
    io.containers.autoupdate: registry
spec:
  containers:
    - name: Foundry_VTT
      image: docker.io/felddy/foundryvtt
      env:
        - name: TZ
          value: "America/New_York"
        - name: FOUNDRY_USERNAME
          value: "XXXXXXXXXX"
        - name: FOUNDRY_PASSWORD
          value: "rEdAcTeD"
        - name: FOUNDRY_ADMIN_KEY
          value: "ReDaCtEd"
      ports:
        - name: foundry
          containerPort: 30000
          hostPort: 30000
          protocol: TCP
      volumeMounts:
        - name: foundry_data
          mountPath: /data:z
  dnsPolicy: Default
  restartPolicy: Never

  volumes:
    - name: foundry_data
      hostPath:
        path: /home/andy/.podman/foundry_vtt/data
```

I ran `podman unshare chown -R 1000:1000 /home/andy/.podman/foundry_vtt`

Then I ran `podman play kube ./foundryvtt.yaml` and it's up and running!

Please tell me if I did something wrong.

**Reply by Drazev** [reply]
I have resolved this change in a branch and placed a MR.

This was a result of two problems.
1) The ownership of the mounted volume and some files was still root, and not the non-root user created
2) The Docker-compose file from foundry-kanka re-creates the /data volume. This will replace any /data folder in the base image with a new version that belongs to the root user. It must be removed for the changes in my PR to work and it should be documented that users do not do this.

See #1241 
and https://github.com/eXaminator/kanka-foundry/pull/154

**Comment by Inch-high** [comment]
Anyone else managed to get this latest image working on Unraid, I've tried setting terms etc. However it just starts and then immediately stops, nothing showing up in the logs. I also noitced a bunch of deprecated variables seem to still be set on the unraid install, maybe this just needs some love?

**Comment by olterman** [comment]
I am also failing to get this up and running again I have changed permissions to 1000:1000 on the Data folder 
`sudo chown -R 1000:1000 *`
I am running with podman compose up with the following docker-compose yaml
```
services:
  foundry:
    image: docker.io/felddy/foundryvtt:latest
    hostname: [redacted]
    init: true
    restart: "unless-stopped"
    volumes:
        - /home/self-hosted/FoundryVTT/Data:/data
    environment:
      - FOUNDRY_PASSWORD=[redacted]
      - FOUNDRY_USERNAME=[redacted]
      - FOUNDRY_ADMIN_KEY=[redacted]
      #- FOUNDRY_SSL_CERT=foundry.crt
      #- FOUNDRY_SSL_KEY=foundry.key
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
```
I don't know what else to do
