### DISCUSSION TITLE
World failing to auto load

### DISCUSSION THREAD

**Discussion by TR7Mike** [felddy/foundryvtt-docker#1207] [Q&A] [answered]
I have a docker compose I've been running via a stack in portainer. Has been working fine, but with a couple of issues (license and world auto load). I've fixed the license now, but I can't figure out why the world won't auto load.

```yml
foundryvtt-live:
    image: felddy/foundryvtt:12.331
    container_name: foundryvtt-live
    hostname: foundryvtt-live
    #env_file:
    #  - stack.env
    environment:
      - TZ=Europe/London
      - PUID=1000
      - PGID=1000      
      - FOUNDRY_HOSTNAME=foundryvtt-live
      - CONTAINER_CACHE=/data/container_cache
      - FOUNDRY_ADMIN_KEY=MyPass
      #- FOUNDRY_PASSWORD="mypass"
      #- FOUNDRY_USERNAME="mike@tr7v8.com"
      - FOUNDRY_LICENSE_KEY="MyKey"
      #- FOUNDRY_RELEASE_URL=""
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - FOUNDRY_PROTOCOL=4
      - CONTAINER_PRESERVE_CONFIG=true
      - FOUNDRY_TELEMETRY=false
      - FOUNDRY_WORLD="maincampaign"
      - CONTAINER_VERBOSE=true
    volumes:
      - /home/linux/docker_volumes/foundryvtt-live:/data      
    ports:
      - "9100:30000"
    restart: unless-stopped
```

Here is the output from the portainer log:

```console
Entrypoint | 2025-05-01 20:40:07 | [debug] Timezone set to: UTC
Entrypoint | 2025-05-01 20:40:07 | [info] Starting felddy/foundryvtt container v12.331.0
Entrypoint | 2025-05-01 20:40:07 | [debug] CONTAINER_VERBOSE set.  Debug logging enabled.
Entrypoint | 2025-05-01 20:40:07 | [debug] Running as: uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
Entrypoint | 2025-05-01 20:40:07 | [debug] Environment:
CONTAINER_CACHE=/data/container_cache
CONTAINER_PRESERVE_CONFIG=true
CONTAINER_VERBOSE=true
FOUNDRY_ADMIN_KEY=[REDACTED]
FOUNDRY_HOME=/home/foundry
FOUNDRY_HOSTNAME=foundryvtt-live
FOUNDRY_LICENSE_KEY=[REDACTED]
FOUNDRY_MINIFY_STATIC_FILES=true
FOUNDRY_PROTOCOL=4
FOUNDRY_TELEMETRY=false
FOUNDRY_VERSION=12.331
FOUNDRY_WORLD=maincampaign
HOME=/root
HOSTNAME=foundryvtt-live
NODE_VERSION=18.20.3
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

0

0
PWD=/home/foundry
SHLVL=1
TZ=Europe/London
YARN_VERSION=1.22.19
Entrypoint | 2025-05-01 20:40:07 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2025-05-01 20:40:07 | [info] Using CONTAINER_CACHE: /data/container_cache
Entrypoint | 2025-05-01 20:40:07 | [info] Installing Foundry Virtual Tabletop 12.331
Entrypoint | 2025-05-01 20:40:07 | [debug] Checking mime-type of release file.
Entrypoint | 2025-05-01 20:40:07 | [debug] Found mime-type: application/zip
Entrypoint | 2025-05-01 20:40:07 | [debug] Extracting release file.
Entrypoint | 2025-05-01 20:40:09 | [debug] Installation completed.
Entrypoint | 2025-05-01 20:40:09 | [info] Preserving release archive file in cache.
Entrypoint | 2025-05-01 20:40:09 | [debug] CONTAINER_CACHE_SIZE is not set. Skipping cache cleanup.
Entrypoint | 2025-05-01 20:40:09 | [debug] Patching GUI update and configuration messages.
Entrypoint | 2025-05-01 20:40:09 | [info] Not modifying existing installation license key.
Entrypoint | 2025-05-01 20:40:09 | [info] Setting data directory permissions.
Entrypoint | 2025-05-01 20:40:09 | [debug] Setting ownership of /data to foundry:foundry.
Entrypoint | 2025-05-01 20:40:09 | [debug] Completed setting directory permissions.
Entrypoint | 2025-05-01 20:40:09 | [info] Starting launcher with uid:gid as foundry:foundry.
Entrypoint | 2025-05-01 20:40:09 | [debug] Waiting for child pid: 53 to exit.
Launcher | 2025-05-01 20:40:09 | [debug] Ensuring /data/Config directory exists.
Launcher | 2025-05-01 20:40:09 | [warn] CONTAINER_PRESERVE_CONFIG is set: Not updating options.json
Launcher | 2025-05-01 20:40:09 | [warn] CONTAINER_PRESERVE_CONFIG is set: Not updating admin.txt
Launcher | 2025-05-01 20:40:09 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2025-05-01 19:40:10 | [info] Running on Node.js - Version 18.20.3
FoundryVTT | 2025-05-01 19:40:10 | [info] Foundry Virtual Tabletop - Version 12 Build 331
FoundryVTT | 2025-05-01 19:40:10 | [info] User Data Directory - "/data"
FoundryVTT | 2025-05-01 19:40:10 | [info] Application Options:
{
  "awsConfig": null,
  "compressSocket": false,
  "compressStatic": true,
  "cssTheme": "foundry",
  "fullscreen": false,
  "hostname": null,
  "hotReload": false,
  "language": "en.core",
  "localHostname": null,
  "passwordSalt": null,
  "port": 30000,
  "protocol": 4,
  "proxyPort": null,
  "proxySSL": false,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "telemetry": false,
  "updateChannel": "stable",
  "upnp": false,
  "upnpLeaseDuration": null,
  "world": null,
  "deleteNEDB": false,
  "serviceConfig": null,
  "adminPassword": "••••••••••••••••",
  "noBackups": false
}

FoundryVTT | 2025-05-01 19:40:10 | [info] Software license verification succeeded
FoundryVTT | 2025-05-01 19:40:10 | [info] Server started and listening on port 30000
FoundryVTT | 2025-05-01 19:40:26 | [info] Created client session 22df4987d7169a99dffba4dc
FoundryVTT | 2025-05-01 19:40:26 | [warn] The module "midi-srd" contains a pack with an invalid name "Midi SRD Items". Pack names containing any character that is non-alphanumeric or an underscore will cease loading in version 14 of the software.
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
```

Seems to indicate that the world isn't being passed through. I have tried putting the environment variables in an env file, but that doesn't work either (same no launch issue).
