### DISCUSSION TITLE
How do you change the listening port of the container?

### DISCUSSION THREAD

**Discussion by klatschi** [felddy/foundryvtt-docker#134] [Q&A] [answered]
Dear Community,

first of all - thanks for providing this image, it really helped me hosting my Foundry VTT on my Synology NAS. Unfortunately, I am a mere novice when it comes to server administration and Docker, and I ran into some issues.

I purchased a second License Key to being able to run two worlds in parallel. So I created a second container and defined the variable `FOUNDRY_LICENSE_KEY` to a specific key to avoid any problems. I changed the local port to `40000` so it dosn't interfere with my other instance that runs perfectly well on `30000`. Also opened the port in my router.

Now, everything is running smoothly, the container starts working however I cannot access it via browser. Looking at the protocol, it reports:
`FoundryVTT | 2020-12-22 12:35:05 | [info] Server started and listening on port 30000 | stdout`

So, I set up the container a second time, trying to change the command beneath the environment variables.

![image](https://user-images.githubusercontent.com/75750249/102894727-d4f1ce80-4463-11eb-9880-32b9d6457c30.png)

Standard command looks like this: 
`resources/app/main.js --port=30000 --headless --noupdate --dataPath=/data`

So I copied that and just changed the port to `40000` but it says there's an error in the command and I really have no clue what docker wants me to put there, since I know next to nothing about it :-(

**Comment by felddy** [comment, marked as answer]
Good question... 

The server in the container will always listen on port `30000`.  This port is exposed by the container: https://github.com/felddy/foundryvtt-docker/blob/d7bbea8063e5cbf8cc93ef114aca843be45d299d/Dockerfile#L78

You need only [publish](https://docs.docker.com/config/containers/container-networking/#published-ports) the port to your desired target.  In your case `40000`.  There is no need to modify the entry point, or the arguments.  I'm not familiar with the Synology GUI but I expect the configuration you are searching for is in the "Netzwerk" tab.  

This is how it would be accomplished using the CLI:
```console
docker run \
  --env FOUNDRY_USERNAME='<your_username>' \
  --env FOUNDRY_PASSWORD='<your_password>' \
  --publish 40000:30000/tcp \
  --volume <your_data_dir>:/data \
  felddy/foundryvtt:release
```

**Reply by klatschi** [reply]
Thanks, I could change the port, so the local port is 40000 now, while the container port remains 30000.

![Bildschirmfoto 2020-12-22 um 16 29 33](https://user-images.githubusercontent.com/75750249/102905092-f0b0a100-4472-11eb-9a21-968445187593.png)

That worked, thanks!

**Comment by cmleinz** [comment]
Hey! I think I'm having the same issue but I'm using docker-compose. Is this not the correct usage? I've starred out sensitive fields but this configuration works with my primary server but not when I try to create a new one on a different port.


```yml
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: ****
    init: true
    volumes:
      - type: bind
        source: ****
        target: /data
    environment:
      - FOUNDRY_PROXY_PORT=true
      - FOUNDRY_PASSWORD=****
      - FOUNDRY_USERNAME=****
      - FOUNDRY_ADMIN_KEY=****
      - FOUNDRY_LICENSE_KEY=****
    ports:
      - target: 30001
        published: 30001
        protocol: tcp
```

**Reply by felddy** [reply]
The `target` port should always be: `30000`

So your `ports` block should look like:
```yml
    ports:
      - target: 30000
        published: 30001
        protocol: tcp
```

See: 
- https://docs.docker.com/compose/compose-file/compose-file-v3/#ports

Also, `FOUNDRY_PROXY_PORT` should be an integer.

**Reply by ofmars87** [reply]
I am running into a similar issue. I've got the containers running side by side just fine, but I'm having trouble reaching them externally through my reverse proxy set up. I use traefik:

```
services:
  foundry:
    image: felddy/foundryvtt:release
    labels:
        - "traefik.enable=true"
        - "traefik.http.routers.foundry-aj.rule=Host(`ajfoundry.xxxxx`)"
        - "traefik.http.routers.foundry-aj.entrypoints=https"
        - "traefik.http.routers.foundry-aj.tls=true"
        - "traefik.http.services.foundry-aj.loadbalancer.server.port=30001"

    hostname: foundry-aj
    volumes:
      - type: bind
        source: /root/foundry/aj
        target: /data
    environment:
      - FOUNDRY_PASSWORD=xxxxx
      - FOUNDRY_USERNAME=xxxxx
      - FOUNDRY_ADMIN_KEY=xxxxx
      - FOUNDRY_PROXY_PORT=30001
    ports:
      - target: 30000
        published: 30001
        protocol: tcp
    networks:
      - proxy

networks:
  proxy:
    external: true

```

Everything matches my working config except for the relevant ports and names, and I've triple checked DNS in both my local and domain provider settings. trying to navigate to the url gives a bad gateway, navigating to the ip at port 30001 works fine. also looks good in traefik dashboard:
![image](https://github.com/user-attachments/assets/038f3275-bcb1-423e-8638-346855a213fd)
