### DISCUSSION TITLE
How to prevent prompt to accept license when container is recreated.

### DISCUSSION THREAD

**Discussion by yougotborked** [felddy/foundryvtt-docker#159] [Q&A] [answered]
Hi, is there any way to automatically accept the license on startup? I feel like if I've already done it, I shouldn't have to do it again.

Mabye this is more of a foundry quirk, than something related to your container?

**Comment by felddy** [comment]
Hey @yougotborked .  Once you accept the license you should not need to accept it again unless you delete the signed license file, or the license changes.  This happened between `0.7.9` and `0.8.0`. 

I know accepting a license is annoying, but that isn't something that I would want to automate.  It serves a purpose, and hiding it from the user would be a disservice.  

That said, I do appreciate the issue.  I understand how this would be useful.  But I think you'll find that it is rare that you'll need to reaccept it.  

Again, thank you for the issue, and let me know if there are any other ways I can make the container more useful to you.

**Comment by yougotborked** [comment, marked as answer]
Sorry if I was not clear,

I am caching the license (I think?), but for some reason every time I restart the container I have to re-accept the licence. the version did not upgrade or change.

These are the env vars I am setting,
```yml
version: '3.8'

services:
  foundry:
    image: felddy/foundryvtt:release
    container_name: foundry
    init: true
    restart: unless-stopped
    environment:
      - PUID
      - PGID
      - TZ
      - TIMEZONE
      - FOUNDRY_HOSTNAME
      - CONTAINER_CACHE
      - FOUNDRY_PROXY_PORT
      - FOUNDRY_PROXY_SSL
      - FOUNDRY_UID
      - FOUNDRY_UPNP
      - FOUNDRY_ADMIN_KEY=${FOUNDRY_ADMIN_KEY}
      - FOUNDRY_USERNAME=${FOUNDRY_USERNAME}
      - FOUNDRY_PASSWORD=${FOUNDRY_PASSWORD}
    ports:
      - 30000:30000/tcp
    volumes:
      - ${DOCKER_NFS}/var/foundry:/data
```

And some lines from the startup log
<details><summary>logs</summary>
<p>

```console
Entrypoint | 2021-03-12 20:52:03 | [info] Starting felddy/foundryvtt container v0.7.9
Entrypoint | 2021-03-12 20:52:03 | [info] Foundry Virtual Tabletop 0.7.9 is installed.
Entrypoint | 2021-03-12 20:52:03 | [info] Not modifying existing installation license key.Entrypoint | 2021-03-12 20:52:03 | [info] Setting data directory permissions.
Entrypoint | 2021-03-12 20:53:48 | [info] Starting launcher with uid:gid as 65534:foundry.Launcher | 2021-03-12 20:53:48 | [info] Generating options.json file.
Launcher | 2021-03-12 20:53:48 | [info] Setting 'Admin Access Key'.
Launcher | 2021-03-12 20:53:48 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2021-03-12 20:53:50 | [info] Foundry Virtual Tabletop - Version 0.7.9
FoundryVTT | 2021-03-12 20:53:50 | [info] Running on Node.js - Version 12.20.0
FoundryVTT | 2021-03-12 20:53:50 | [info] Loading data from user directory - /data
FoundryVTT | 2021-03-12 20:53:50 | [info] Application Options:
{
  "port": 30000,
  "upnp": true,
  "fullscreen": false,
  "hostname": "foundry.----------",
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "awsConfig": null,
  "dataPath": "/data",
  "proxySSL": true,
  "proxyPort": 443,
  "minifyStaticFiles": false,
  "updateChannel": "release",
  "language": "en.core",
  "world": null,
  "serviceConfig": null,
  "isElectron": false,
  "isNode": true,
  "isSSL": false,
  "demo": false,
  "noupdate": true,
  "adminKey": "****************"
}
FoundryVTT | 2021-03-12 20:53:50 | [error] License verification failed. Please confirm your Foundry Virtual Tabletop software license
FoundryVTT | 2021-03-12 20:53:50 | [info] Requesting UPnP port forwarding to destination 30000
FoundryVTT | 2021-03-12 20:53:51 | [info] Server started and listening on port 30000
FoundryVTT | 2021-03-12 20:54:10 | [info] Created client session f7vag3yimwcjgtg0nlzm8p62
FoundryVTT | 2021-03-12 20:57:10 | [info] Created client session 6pme3i1a6u6ae2huj776inb6
FoundryVTT | 2021-03-12 21:02:50 | [info] License signature successfully created. Thank you and please enjoy Foundry Virtual Tabletop.
FoundryVTT | 2021-03-12 21:02:50 | [info] License verification 
```
</p>
</details>

**Reply by felddy** [reply]
Thank you for clarifying.    The license is tied to the machine name.  You need to set the `hostname` name of the container so that Foundry sees it as the same machine.  Otherwise the hostname is randomly generated.  

See: https://github.com/felddy/foundryvtt-docker#configuration-management

When using Docker compose specify `hostname` like this:
```yaml
---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: <your_data_dir>
        target: /data
    environment:
      - FOUNDRY_PASSWORD=<your_password>
      - FOUNDRY_USERNAME=<your_username>
      - FOUNDRY_ADMIN_KEY=atropos
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
```

Use the `--hostname` option to `docker run` if using the command line. 

Let me know if this helps.

**Reply by unites** [reply]
> Thank you for clarifying. The license is tied to the machine name. You need to set the `hostname` name of the container so that Foundry sees it as the same machine. Otherwise the hostname is randomly generated.

Not to resurrect the dead but might be worth having the clarification tied directly to this ticket as this showed up in the google search. 

When you say set the hostname so that Foundry sees it as the "same machine" do you mean you should have you rdocker hosts hostname match your containers hostname?  Example;  hostname `dockerserver` is running container named `foundry` with  hostname set to `dockerserver`?  This doesn't seem to resolve the fore-mentioned error so I think I am misreading your statement some how.

**Reply by Kreakdude** [reply]
I had this exact problem and I followed these directions like so and it solved it.
> container_name: foundry
> hostname: foundry

**Reply by joneshf** [reply]
For those of us using k8s, one thing you can do is use a [StatefulSet](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset) rather than a [Deployment](https://kubernetes.io/docs/concepts/workloads/controllers/deployment/). Full caveats about using a StatefulSet over a Deployment apply. But importantly, StatefulSets have [stable, unique network identifiers](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/#using-statefulsets).

The long and short is that a StatefulSet will generate a hostname like `foundry-vtt-0` for your first (only?) Pod each time it's created. Whereas a Deployment will generate a hostname like `foundry-vtt-123456abcdef-123abc` one time the Pod is created, and a hostname like `foundry-vtt-abcdef123456-abc123` the next time the Pod is created.

**Reply by dbeniciorj** [reply]
> container_name: foundry
> hostname: foundry

Just adding what worked for me:
```
    container_name: foundry
    hostname: foundry
    environment:
      - FOUNDRY_HOSTNAME=foundry
```
