### DISCUSSION TITLE
How can I share the /data/Data directory between two running Foundry containers?

### DISCUSSION THREAD

**Discussion by Nicoolai** [felddy/foundryvtt-docker#166] [Q&A] [answered]
Hi,
So, I love this container image already but I have a bit of an edge-case (probably) that I'm trying to make work.
I am running two instances on the same host. I want them to share the same `data/Data` folder.
I've tried to symlink my way out of it, so instance 2 points to the same place on my host.

However, with symlink, I get an issue when it tries to `chown` the folders on startup.
So, following some other discussions in here, I have set `FOUNDRY_GID`, `FOUNDRY_UID` and `CONTAINER_PRESERVE_OWNER`. 
This seems to be in the right direction, I no longer get fatal chown issues, but unfortunately it means that it doesn't see my symlink as a folder (I think) so it tries to `mkdir` the `Data` folder, causing another exception as the symlink is there, with the same name.

Any ideas on how I could get this setup working?

**Comment by felddy** [comment, marked as answer]
I'm glad the container is working well for you.  I have an idea that I think will work.

So, I'm pretty sure Docker will be unhappy trying to resolve a symlink across volumes.

In the second container try mounting the `Data` directory (from the first) on top of the `data` mount of second.  I just tried this and it seems to work well.  (see below).  

It's a little confusing with all the things named "data".


Host:
```console
└── parent
    ├── data
    |  └── Data
    └── data1
```

Container 1:
```console
└── /data (host data)
    └── Data
```

Container 2:
```console
└── /data (host data1)
    └── Data (host data/Data)
```


```yml
---
version: "3.8"

secrets:
  credentials:
    file: credentials-mine.json

services:
  foundry0:
    image: felddy/foundryvtt:release
    hostname: felddy_foundryvtt
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_VERBOSE=true
      - TIMEZONE=US/Eastern
      - FOUNDRY_UID=501
      - FOUNDRY_GID=20
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - FOUNDRY_UPNP=false
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
  foundry1:
    image: felddy/foundryvtt:release
    hostname: felddy_foundryvtt_1
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: ./data1
        target: /data
      - type: bind
        source: ./data/Data
        target: /data/Data
      - type: bind
        source: ./data/container_cache
        target: /data/container_cache
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_VERBOSE=true
      - TIMEZONE=US/Eastern
      - FOUNDRY_UID=501
      - FOUNDRY_GID=20
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - FOUNDRY_UPNP=false
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: "30000"
        published: "30001"
        protocol: tcp
```

Couple of things to be careful with:
* This black magic is probably breaking some of the assumptions that Foundry is making in order to protect the integrity of the `Data` files.  I'd be careful accessing the same world on both instances.
* The [FoundryVTT License](https://foundryvtt.com/article/license/) has terms regarding player access to duplicate instances sharing a key. 

Let me know if this works for you.
