### DISCUSSION TITLE
How to set CONTAINER_PRESERVE_OWNER for multiple directories.

### DISCUSSION THREAD

**Discussion by hugoprudente** [felddy/foundryvtt-docker#168] [Q&A] [answered]
Hi Felddy, 

Starting a discussion to check if makes sense the feature change to allow multiple directories.

Today when I deploy my system besides a `/data/Data/assets` I may have other folders that I want to share with my game instances that should be read only. 

Today the way the prune works, it only exclude 1 given directory.

```
find /data -regex "${CONTAINER_PRESERVE_OWNER:-}" -prune -o -exec chown "${FOUNDRY_UID:-foundry}:${FOUNDRY_GID:-foundry}" {} +
```
I'm still thinking in a way to improve the search that doesn't cost much performance to the system so we can use commanDelimitedList to the CONTAINER_PRESERVE_OWNER.

Any thoughts if this makes sense and if it's a thing we should work in change?

**Comment by felddy** [comment, marked as answer]
Hi Hugo,

Since the `CONTAINER_PRESERVE_OWNER` variable accepts a regular expression you can just add an "or" and an additional term.  

For example if you had two asset directories you want to preserve ownership on:
  * `/data/Data/assets`
  * `/data/Data/more-assets`

Setting `CONTAINER_PRESERVE_OWNER` to `/data/Data/assets\|/data/Data/more-assets` will cause both paths to be pruned and not passed to `chown`.  

I tested this with `docker-compose` and it acted as expected:

```yml
---
version: "3.8"

secrets:
  credentials:
    file: credentials-mine.json

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: felddy_foundryvtt
    init: true
    restart: "no"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_PRESERVE_OWNER=/data/Data/assets\|/data/Data/more-assets
      - CONTAINER_VERBOSE=true
      - TIMEZONE=US/Eastern
      - FOUNDRY_UID=501
      - FOUNDRY_GID=20
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
```

Hopefully this helps.  Let me know if it works for you.
