### DISCUSSION TITLE
Cross-origin request error with proxy and FoundryVTT v0.8.6

### DISCUSSION THREAD

**Discussion by coreyjackwilson** [felddy/foundryvtt-docker#210] [Q&A] [answered]
@felddy How do I setup CORS with the 0.8.6 image?

Getting this running docker on my QNAP
![Screen Shot 2021-05-31 at 1 28 40 PM](https://user-images.githubusercontent.com/10590963/120240480-80722c80-c215-11eb-9020-d08fbcc14a42.png)

I assume the HOSTNAME or LOCAL_HOSTNAME envs maybe?

**Comment by thefarwind** [comment]
I'm getting the same issue -- here are my server and nginx configs

For my cors error:

container config (see below for full docker-compose):
```yaml
---
- CONTAINER_VERBOSE=true
- FOUNDRY_PROXY_SSL=true
- FOUNDRY_PROXY_PORT=443
- FOUNDRY_HOSTNAME=<hostname>
```

nginx config:

```nginx
server {
    listen 443 ssl http2;
    server_name <hostname>;

    ssl_certificate <path>;
    ssl_certificate_key <path>;

    include /var/www/certbot/conf/options-ssl-nginx.conf;
    ssl_dhparam /var/www/certbot/conf/ssl-dhparams.pem;

    location / {
    client_max_body_size 5M;
    
    # These are important to support WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;
        
        proxy_pass http://foundry:30000;
    }
}
```

request headers:

```http
POST /setup HTTP/2
Host: <hostname>
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Content-Type: application/x-www-form-urlencoded
Content-Length: 44
Origin: https://<hostname>
Connection: keep-alive
Referer: https://<hostname>/setup
Cookie: session=<session>
Upgrade-Insecure-Requests: 1
TE: Trailers
```

docker-compose:

```yaml
version: "3.8"
services:
  nginx:
    image: nginx:alpine
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    restart: "unless-stopped"
    ports:
    - "30080:80"
    - "30443:443"
    volumes: {{ redacted }}
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    restart: "unless-stopped"
    volumes: {{ redacted }}
  foundry:
    image: felddy/foundryvtt:release
    init: true
    restart: "unless-stopped"
    environment:
    - CONTAINER_VERBOSE=true
    - FOUNDRY_PROXY_SSL=true
    - FOUNDRY_PROXY_PORT=443
    - FOUNDRY_HOSTNAME=<hostname>
    volumes:
      - type: bind
        source: ./data
        target: /data
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
    secrets: {{ redacted }}
```

**Comment by felddy** [comment]
I'm away from my system right now so I can't do any testing.  I am keeping an eye on the Discord thread in #troubleshooting.

It does seem that this is not Docker or container-related since there are also reports of this behavior with people using `pm2`.  

When I get back I'll see if I can replicate this.

**Reply by thefarwind** [reply]
cool, let me know if you want any more information about my setup.

**Reply by felddy** [reply]
FYSA: A bug report was opened for this in the [Discord](https://discord.com/channels/170995199584108546/848968607526551592/849040944086646826).


So... I run Foundry behind nginx as well.  I'm not seeing any CORS errors.   Let me post my configs for reference:

`nginx.conf` (partial)
```nginx
   ...
    location /vtt {
        # FoundryVTT routePrefix = "vtt"

        proxy_http_version 1.1;
        access_log /var/log/nginx/upstream_log upstream_logging;

        proxy_read_timeout 90;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Real-IP $remote_addr;

        proxy_pass http://localhost:30000;
    }
```

`docker-compose.yml`
```yml
---
version: "3.7"

secrets:
  credentials:
    file: credentials.json

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: felddy_foundryvtt
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_VERBOSE=true
      - TIMEZONE=US/Eastern
      - FOUNDRY_UID=1000
      - FOUNDRY_GID=100
      - FOUNDRY_HOSTNAME=my.domain
      - FOUNDRY_TURN_MAX_PORT=42252
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_ROUTE_PREFIX=vtt
      - FOUNDRY_UPNP=false
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
        mode: host
      - target: 33478
        published: 33478
        protocol: udp
        mode: host
      - "49152-49252/udp"
```

request headers
```http
POST /vtt/setup HTTP/1.1
Host: my.domain
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:88.0) Gecko/20100101 Firefox/88.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Referer: https://my.domain/vtt/setup
Content-Type: application/json
Origin: https://my.domain
Content-Length: 63
Connection: keep-alive
Cookie: session=xxx
```

I'll keep an eye on this.

**Reply by thefarwind** [reply]
I think CORS is a red herring here. CORS is the browser complaining because you requested a resource from a server which is a different origin than the webpage you're currently visiting, and the resource doesn't have a CORS header.

This is the server complaining because the request isn't coming from the server URL it thinks the request should come from.

My nginx sees my foundry server named 'foundry', so foundry is likely recieving a request from foundry:30000 which is stating it's proxied from my.domain. My guess is foundry isn't configured to trust foundry:30000, so it's returning the error.

MY first guess is yours is working because your nginx connection is forwarding to localhost:30000, and there are special rules for localhost. ~~I'm going to see if I can change my docker config so that the proxy goes to localhost:30000~~ (having issues w/ windows/docker and getting this test going. I'll probably not get to it today).

**Reply by thefarwind** [reply]
Found the fix, at least for my configuration!

the new proxy configuration required the following line set (you'll notice it's in your configuration):

```nginx
proxy_set_header Host $http_host;
```

Once I added this to my nginx configuration, everything started working again.

**Reply by felddy** [reply]
If I comment out the `proxy_set_header Host $host;` line from my nginx configuration I can reproduce the issue as described.  

Great job finding the solution.

**Reply by coreyjackwilson** [reply]
> Found the fix, at least for my configuration!
> 
> the new proxy configuration required the following line set (you'll notice it's in your configuration):
> 
> ```nginx
> proxy_set_header Host $http_host;
> ```
> 
> Once I added this to my nginx configuration, everything started working again.

So I guess the solution requires that you use a proxy now?

**Reply by felddy** [reply]
@coreyjackwilson Can you provide more information about your setup?  Are you seeing this error without a proxy?

**Reply by coreyjackwilson** [reply]
> @coreyjackwilson Can you provide more information about your setup? Are you seeing this error without a proxy?

For sure @felddy 

I am running the image on QNAPs docker solution (called Container Station), basically just runs the image without a proxy accessible at some port on the same machine. I was considering setting HOSTNAME to the same IP as the machine, but hadn't tried that yet.

**Reply by felddy** [reply]
Thanks @coreyjackwilson that is helpful!

So I do have a QNAP here and I was able to spin up `:0.8.6` in the Container Station:
![image](https://user-images.githubusercontent.com/3229435/120371662-1f655a00-c2e4-11eb-96f9-13348315c19e.png)

I used the `+Create Application` button in the "Create" tab to create the container.  I used the following docker-compose yml:

```yml
version: '3'

services:
  foundry:
    image: felddy/foundryvtt:0.8.6
    hostname: felddy_foundryvtt
    restart: "no"
    volumes:
      - /share/Container/foundry_data:/data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_PATCHES=/data/container_patches
      - CONTAINER_VERBOSE=true
      - FOUNDRY_PASSWORD=<password>
      - FOUNDRY_USERNAME=<username>
      - TIMEZONE=US/Eastern
      - FOUNDRY_ADMIN_KEY=<admin_password>
      - FOUNDRY_HOSTNAME=qnap.lan
      - FOUNDRY_PROXY_PORT=
      - FOUNDRY_PROXY_SSL=false
      - FOUNDRY_ROUTE_PREFIX=
      - FOUNDRY_SSL_CERT=
      - FOUNDRY_SSL_KEY=
      - FOUNDRY_UPNP=false
      - FOUNDRY_WORLD=
    ports:
      - "400:30000"
 ```

I was also able to access it via Firefox at both its DNS name and IP address.  That is:
- http://qnap.lan:400
- http://10.10.10.10:400

Did you use the wizard in "Container Station" to create the container, or did you use the `+Create Application` button?
