### DISCUSSION TITLE
felddy foundry-docker with traefik.

### DISCUSSION THREAD

**Discussion by CaosFR** [felddy/foundryvtt-docker#254] [Q&A] [answered]
Hi,

Since few month I use "direckthit/fvtt-docker" with traefik and portainer.
I have follow this tutorial (https://benprice.dev/posts/fvtt-docker-tutorial/) and my foundry work pretty well but....this repository and his github (https://github.com/BenjaminPrice/fvtt-docker) look like outdated.
My foundry serveur become more and more instable after new update.

May I request your help for use your good and update repository ?
I have create a docker-compose.yml but when I start it, I have this warning :
WARNING: Some networks were defined but are not used by any service: proxy
When I go to https://foundry.rp.fr/ I have a 404 not found.
The error seems to come from the syntax from the networks parameter.

Edit : Solve, new docker-compose.yml if it's help something
```yml
version: "3.3"

services:
  foundry:
    image: felddy/foundryvtt:latest
    container_name: foundry
    init: true
    restart: "unless-stopped"
    networks:
      - proxy
    volumes:
      - type: bind
        source: /home/roleplay/foundrydata
        target: /data
    environment:
      - FOUNDRY_PASSWORD=xxxx
      - FOUNDRY_USERNAME=xxxx
      - FOUNDRY_ADMIN_KEY=xxxx
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foundryvtt.entrypoints=http"
      - "traefik.http.routers.foundryvtt.rule=Host(`xx.xx.xx`)"
      - "traefik.http.middlewares.foundryvtt-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.foundryvtt.middlewares=foundryvtt-https-redirect"
      - "traefik.http.routers.foundryvtt-secure.entrypoints=https"
      - "traefik.http.routers.foundryvtt-secure.rule=Host(`xx.xx.xx`)"
      - "traefik.http.routers.foundryvtt-secure.tls=true"
      - "traefik.http.routers.foundryvtt-secure.tls.certresolver=http"
      - "traefik.http.routers.foundryvtt-secure.service=foundryvtt"
      - "traefik.http.services.foundryvtt.loadbalancer.server.port=xxxx"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```
