### DISCUSSION TITLE
2 Foundry-Instance - shared data-source

### DISCUSSION THREAD

**Discussion by JuIez** [felddy/foundryvtt-docker#259] [Q&A] [answered]
Hey Guys,
I tried to get 2 Foundry-Instance running with the same data-source. 
If I put them to 2 different locations, there won't be any problems, but as soon as I try to get them to the same, I can't access the second one.

Is there a way to fix it? Since I use a lot of Add-ons and share maps between multiple worlds, it would be really useful. 
Thanks in advance :D

```
version: "3.8"

services:
   foundry:
     image: felddy/foundryvtt:release
     container_name: foundryVTT_Test
     init: true
     restart: "unless-stopped"
     volumes:
       - type: bind
         source: ./data/foundry/
         target: /data
     environment:
       - FOUNDRY_USERNAME=---
       - FOUNDRY_PASSWORD=---
       - FOUNDRY_ADMIN_KEY=---
       - FOUNDRY_LICENSE_KEY=Licens_Key
       - FOUNDRY_GID=1000
       - FOUNDRY_UID=1000
     ports:
       - 30000:30000
   foundry_2:
     image: felddy/foundryvtt:release
     container_name: foundryVTT_2
     init: true
     restart: "unless-stopped"
     volumes:
       - type: bind
         source: ./data/foundry/
         target: /data
     environment:
       - FOUNDRY_USERNAME=---
       - FOUNDRY_PASSWORD=---
       - FOUNDRY_ADMIN_KEY=---
       - FOUNDRY_LICENSE_KEY=Licens_Key
       - FOUNDRY_GID=1000
       - FOUNDRY_UID=1000
     ports:
       - target: "30000"
         published: "30010"
         protocol: tcp
```

![image](https://user-images.githubusercontent.com/44580956/142744164-04b1b49f-38f0-4284-8a06-fce430c0af0a.png)
