### DISCUSSION TITLE
Blank Screen, no admin login box

### DISCUSSION THREAD

**Discussion by unites** [felddy/foundryvtt-docker#278] [Q&A] [answered]
I am using https://nginxproxymanager.com/ for a reverse proxy.  My config is as below.  After the release of v9 it appears I can't login to the server.  If I pass through 30000 via http everything works. 

I get the blank backdrop no login prompt.

```yaml
version: "3.8"

services:
  avernus:
    image: felddy/foundryvtt:release
    container_name: foundry-avernus
    hostname: <docker host hostname>
    privileged: true
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /srv/Avernus/data
        target: /data
    environment:
      - FOUNDRY_PASSWORD=<password>
      - FOUNDRY_USERNAME=<name>
      - FOUNDRY_ADMIN_KEY=<admin password>
      - FOUNDRY_PROXY_SSL=True
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_HOSTNAME=<docker host hostname>
      - FOUNDRY_LOCAL_HOSTNAME=<docker host hostname>
      - CONTAINER_CACHE=/data/container_cache
      - FOUNDRY_LICENSE_KEY=<my license>
    ports:
      - 30000:30000
    networks:
      - frontend
      
networks:
  frontend:
    external:
      name: frontend
```
Proxy
```json
{
  "id": 2,
  "created_on": "2022-01-24 01:56:51",
  "modified_on": "2022-01-24 02:52:44",
  "owner_user_id": 1,
  "domain_names": [
    "rpg.example.com"
  ],
  "forward_host": "avernus",
  "forward_port": 30000,
  "access_list_id": 0,
  "certificate_id": 2,
  "ssl_forced": false,
  "caching_enabled": false,
  "block_exploits": true,
  "advanced_config": "",
  "meta": {
    "letsencrypt_agree": false,
    "dns_challenge": false
  },
  "allow_websocket_upgrade": false,
  "http2_support": true,
  "forward_scheme": "http",
  "enabled": 1,
  "locations": [],
  "hsts_enabled": false,
  "hsts_subdomains": false
}
```

**Comment by felddy** [comment, marked as answer]
What you are describing is the behavior of a proxy that is not handling web sockets properly.

Probably the same issue that was documented here in #118.

An example of a working nginx proxy configuration can be found here: 
https://github.com/felddy/foundryvtt-docker/tree/improvement/cookbooks#hosting-behind-nginx-with-tls

Also take a look at FoundryVTT's page about it:
https://foundryvtt.com/article/nginx/

**Reply by unites** [reply]
Yep that was it,  just needed flip the socket slider to enabled under host config in Nginx Network Manager.

**Comment by DerJJ** [comment]
I'm gonna hijack this, cause I have the same issue, but with a different proxy (traefik).
Although I understand that this seems to be a traefik configuration issue, I will still ask this here because others might also run into this, and maybe we find a solution.

Unfortunately, for traefik, there is no on/off switch for websockets, the doc says it should work right out of the box.
Thus, there is barely any mentioning of websockets in the traefik doc.

Foundry KB also has nothing on Traefik as reverse proxy (at least I couldn't find it).

As soon as I turn on TLS, it doesn't work anymore. (insecure) websockets work fine, secure websockets fall apart. 
I added the
```
      - FOUNDRY_PROXY_SSL=True
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_HOSTNAME=<docker host hostname>
```
part, other services with TLS (without wss) work fine.
I switched to portainer while also adding the certifcate resolver, but I don't think this is related.

Any further ideas?

**Reply by unites** [reply]
This is likely not the issue but I found that matching my hostname from host to container resolved issues...
```yaml
  vtt:
    image: felddy/foundryvtt:release
    container_name: foundry-vtt
    hostname: <CONTAINER_HOST>
    privileged: true
    init: true
    restart: "unless-stopped"
    environment:
      - FOUNDRY_PROXY_SSL=True
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_HOSTNAME=<CONTAINER_HOST>
      - FOUNDRY_LOCAL_HOSTNAME=<CONTAINER_HOST>
```

However I am not sure if that would address traefik's specific issues.

I know probably no small thing but Nginx Proxy Manager and Caddy seem to be the solutions most often used by people for VTT (and a lot other self hosting these days), if it's not trivial it might be worth switching over. If you enjoy the text file like modification caddy, GUI then NPM.  I would at least deploy one of them to see if your container will work with an alternate proxy, that would rule out your Portainer/docker-compose config and the problem would be definitely with traefik.
