### DISCUSSION TITLE
CSS Login screen

### DISCUSSION THREAD

**Discussion by Ryach** [felddy/foundryvtt-docker#331] [Q&A]
Could you help me add my own CCS file for Login screen please
how to ad it to yml script

**Comment by felddy** [comment]
I'm assuming you are trying to do something similar to what was documented by @TheEpicSnowWolf here:
- https://github.com/TheEpicSnowWolf/Foundry-VTT-Prettier-Login-Screen
- https://www.reddit.com/r/FoundryVTT/comments/o93svp/08x_compatible_css_for_a_prettier_login_screen/

One way to do this is by using the `CONTAINER_PATCHES` feature documented in the README:
- https://github.com/felddy/foundryvtt-docker#optional-variables

Steps:
1. Set `CONTAINER_PATCHES=/data/container_patches`
1. Create the `container_patches` directory on your data volume.
1. Create a shell script in `container_patches` containing the code to modify the css.  (See example is below)
1. Start the container.

Below is an example shell script that downloads the css from the project mentioned above, and concatenates it onto the stylesheet file. 

### `patch_login_css.sh`
```bash
#!/bin/sh

CSS_PATH="resources/app/public/css/style.css"
CSS_URL="https://raw.githubusercontent.com/TheEpicSnowWolf/Foundry-VTT-Prettier-Login-Screen/5e67554ae1c16ba77775398531b46225bb05b0aa/foundry_login.css"

log "Downloading CSS from $CSS_URL"
curl -s -o /tmp/foundry_login.css $CSS_URL

log "Applying CSS patch"
cat /tmp/foundry_login.css >> $CSS_PATH
```

Please, let me know if this is what you were looking for.

**Reply by Ryach** [reply]
Hi thank you for prompt answer yes it exactly what I'm looking for.
but I'm not sure my knowledge about docker it's limited please clear for me if you can.
I would like to add my custom.css - for changing the login page for example class is:
 #join-game #world-description {.....} and this is in foundry style.css
so for that if I properly understand in my docker-compose.yml i'm adding:

```yaml
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:9
    hostname: my-domain
    init: true
    volumes:
      - type: bind
        source: /home/pi/docker/foundry
        target: /data
        CONTAINER_PATCHES=/home/pi/docker/foundry
    environment:
      - FOUNDRY_PASSWORD=foundry-pass
      - FOUNDRY_USERNAME=my-ussername
      - FOUNDRY_ADMIN_KEY=my-admin-key
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
```

In folder foundry in this case where I have this docker-compose.yml
adding two files:
- patch_login_css.sh
- custom.css
in patch_login_css.sh **(this I'm not sure)**:

```shell
#!/bin/sh

CSS_PATH="/home/pi/docker/foundry/custom.css"

log "Applying CSS patch"
cat /tmp/foundry_login.css >> $CSS_PATH
```
and finally for in my custom.css: 

```css

#join-game #world-description {
    display: none 
}
#myid{
 and other id css code here
}
```

**Reply by felddy** [reply]
Close... you want the `CONTAINER_PATCHES` environment variable in the `environment:` section of the yaml:

```yaml
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:9
    hostname: my-domain
    init: true
    volumes:
      - type: bind
        source: /home/pi/docker/foundry
        target: /data
    environment:
      - FOUNDRY_PASSWORD=foundry-pass
      - FOUNDRY_USERNAME=my-ussername
      - FOUNDRY_ADMIN_KEY=my-admin-key
      - CONTAINER_PATCHES=/data/container_patches
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
```

Your file layout should look similar to this:
```console
    .
    ├── docker-compose.yml
    └── data/
        ├── Config/
        ├── container_cache/
        ├── container_patches/patch_login_css.sh
        ├── Data/
        └── Logs/
```

(in your case `data/` above is `/home/pi/foundry`)

Remember that your execution context within the container is different than outside it.  Your data volume will be mounted at `/data` within the container.  So your patch script will live at `/data/container_patches/patch_login_css.sh`.

**Reply by felddy** [reply]
Here is a simplified version of your script that should work. 

```shell
#!/bin/sh

# Path to the CSS file
SOURCE="/data/custom.css"

# Which file to patch
DEST="resources/app/public/css/style.css"

log "Adding custom CSS..."
log "$SOURCE -> $DEST"

# append the contents of the source file onto the dest
cat $SOURCE >> $DEST 
```

**Reply by Ryach** [reply]
Sorry github is little new for me. 
put on my sh instead of mine version :
```
#!/bin/sh
# Path to the CSS file
SOURCE="/data/custom.css"
# Which file to patch
DEST="resources/app/public/css/style.css"
log "Adding custom CSS..."
log "$SOURCE -> $DEST"
log "ttttttt"
# append the contents of the source file onto the dest
cat $SOURCE >> $DEST

```
from log similar error:
```

Entrypoint | 2022-04-26 18:48:33 | [info] Using CONTAINER_PATCHES: /data/container_patches

Entrypoint | 2022-04-26 18:48:33 | [info] Container patches directory detected.  Starting patch application...

Entrypoint | 2022-04-26 18:48:33 | [info] Sourcing patch from file: /data/container_patches/patch_style_css.sh

Entrypoint | 2022-04-26 18:48:33 | [info] Adding custom CSS...

Entrypoint | 2022-04-26 18:48:33 | [info] /data/custom.css
 -> resources/app/public/css/style.css


Entrypoint | 2022-04-26 18:48:33 | [info] ttttttt

cat: can't open '/data/custom.css
': No such file or directory

Entrypoint | 2022-04-26 18:48:35 | [info] Starting felddy/foundryvtt container v0.8.9 
```
my file custom.css is in foundry folder, also have permission  rwxrwxrwx

**Comment by Ryach** [comment]
Thank you.
I updated my files as you recommended  but still is not work as should probably I'm missing something could you have a look please?
Now my foundry docker looks like this:

```console
.home
└pi
   └docker
         └foundry  
            ├── docker-compose.yml
            ├── custom.css   
            ├── Config/
            ├── container_cache/
            ├── container_patches/patch_style_css.sh
            ├── Data/
            └── Logs/
```
I added to docker-compose.yml:

```yaml
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:9
    hostname: my-domain
    init: true
    volumes:
      - type: bind
        source: /home/pi/docker/foundry
        target: /data
    environment:
      - FOUNDRY_PASSWORD=foundry-pass
      - FOUNDRY_USERNAME=my-ussername
      - FOUNDRY_ADMIN_KEY=my-admin-key
      - CONTAINER_PATCHES=/data/container_patches
    ports:
      - target: 30000
        published: 30000
        protocol: tcp


```
My patch_style_css.sh:

```shell
#!/bin/sh

# Path to the CSS file
SOURCE="/home/pi/docker/foundry/custom.css"

# Which file to patch
DEST="/css/style.css"

# Temporary working directory
TMP_DIR=$(mktemp -d)

# Cleanup in case the script gets stopped prematurely
trap "rm -rf $TMP_DIR" 1 2 3 9 15

log "Adding custom CSS..."
log "$SOURCE -> $DEST"

# This is the important part. This command prints the
# original file ($DEST) and the CSS patch ($SOURCE), then
# it saves the output to a temporary file
cat $DEST $SOURCE > $TMP_DIR/style.css

log "Replacing file..."

# Once the temp file is ready, we need to move replace
# old file with the new and patched file
cp $TMP_DIR/style.css $DEST

log "Should be working now"

# Cleanup
rm -rf $TMP_DIR


```
and my CSS just for testing if it is work: 
```css

#join-game #world-description {
    display: none !important;
}
```
