### DISCUSSION TITLE
v10.263

### DISCUSSION THREAD

**Discussion by felddy** [felddy/foundryvtt-docker#339] [General]
This container supports Foundry VTT **prototype** release `10.263`

See:
- https://foundryvtt.com/releases/10.263

# ⚠️ WARNING # 

From release notes:

> Updates on the Prototype channel provide the implementation of major new features which are likely to introduce unforeseen bugs, breakages to existing game systems or modules, or other problems which will be disruptive to the usage of the software. Do not install this update unless you are doing so for the specific purposes of testing, it is not intended for use in 'live game' scenarios. The purpose of Prototype builds are to allow new experimental features to be tested and to help developers to begin the process of updating packages which are impacted by these changes. If you chose to update to this version you expose yourself to serious risk of having a bad experience. Please take this warning to heart.

<hr /><em>This discussion was created from the release <a href='https://github.com/felddy/foundryvtt-docker/releases/tag/v10.263.0'>v10.263</a>.</em>

**Comment by ArthegaAsdweri** [comment]
How do we install it?
If I pull the container anew it still installs Version 9 - Build 269.

**Reply by felddy** [reply]
Make sure you are not manually setting the `FOUNDRY_VERSION` variable.  

See:
- https://github.com/felddy/foundryvtt-docker/discussions/208

**Reply by ArthegaAsdweri** [reply]
I'm not setting the variable. 
I just pulled the image and the latest build seems to contain Build 269.
Is pulling the "latest" build correct or do I have to specify the image version like felddy/foundryvtt:10x :develop or anything?

**Reply by ArthegaAsdweri** [reply]
```yml
foundry:
    image: felddy/foundryvtt
    container_name: foundry
    restart: unless-stopped
    hostname: fvtt
    domainname: xxx.de
    ports:
      - "30000:30001"
    volumes:
      - /srv/www/docker/foundryVtt:/data
      - ./nginx-proxy/certs:/certs
    environment:
      TZ: Europe/Berlin
      FOUNDRY_USERNAME: xxx
      FOUNDRY_PASSWORD: xxx
      FOUNDRY_ADMIN_KEY: xxx
      FOUNDRY_PROXY_PORT: 443
      FOUNDRY_PROXY_SSL: "true"
      VIRTUAL_HOST: fvtt.xxx.de
      VIRTUAL_PORT: 30000
      LETSENCRYPT_HOST: fvtt.xxx.de
      LETSENCRYPT_EMAIL: admin@xxx.de
```

**Reply by felddy** [reply]
I understand now.  Thanks for posting your `docker-compose.yml` file.

You are using the implicit `:latest` tag.  You'll have to use the `:prerelease` tag to get the pre-release image.

```yml
foundry:
    image: felddy/foundryvtt:prerelease
   ...
```

See:
- https://github.com/felddy/foundryvtt-docker#image-tags
- https://docs.docker.com/engine/reference/commandline/tag/
