### DISCUSSION TITLE
How to run two instances on different ports

### DISCUSSION THREAD

**Discussion by farlo18** [felddy/foundryvtt-docker#348] [Q&A] [answered]
I currently have one docker instance running (which by the way works fantastic, thank you) on port 30000. I have a second license for Foundry and am trying to have another container running on port 30001. Is this something that can work? Below is what spits out in the container logs as you can see it says port 30000 even though the options.json has 30001 listed. I checked the container details and thats below showing its picking up 30000. Thank you for any help or guidance.

```console
Launcher | 2022-05-14 14:13:22 | [warn] CONTAINER_PRESERVE_CONFIG is set: Not updating options.json
Launcher | 2022-05-14 14:13:22 | [warn] CONTAINER_PRESERVE_CONFIG is set: Not updating admin.txt
Launcher | 2022-05-14 14:13:22 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2022-05-14 14:13:24 | [info] Running on Node.js - Version 16.14.2
FoundryVTT | 2022-05-14 14:13:24 | [info] Foundry Virtual Tabletop - Version 9 Build 269
FoundryVTT | 2022-05-14 14:13:24 | [info] Loading data from user directory - /data
FoundryVTT | 2022-05-14 14:13:24 | [info] Application Options:
FoundryVTT | 2022-05-14 14:13:24 | [warn] Software license requires signature.
{
  "port": 30000,
  "upnp": true,
  "fullscreen": false,
  "hostname": "***.***.com",
  "localHostname": null,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "awsConfig": null,
  "dataPath": "/data",
  "proxySSL": true,
  "passwordSalt": null,
  "proxyPort": 443,
  "serviceConfig": null,
  "updateChannel": "release",
  "language": "en.core",
  "isNode": true,
  "isElectron": false,
  "world": null,
  "compressStatic": true,
  "upnpLeaseDuration": null,
  "isSSL": false,
  "noupdate": true,
  "demo": null,
  "adminKey": "****************"
  "noIPDiscovery": false,
} 
FoundryVTT | 2022-05-14 14:13:24 | [warn] Software license requires signature.
FoundryVTT | 2022-05-14 14:13:24 | [info] Requesting UPnP port forwarding to destination port 30000
FoundryVTT | 2022-05-14 14:13:24 | [info] Server started and listening on port 30000
```

PORT CONFIGURATION | 0.0.0.0:30001  30001/tcp:::30001  30001/tcp
-- | --
CMD | resources/app/main.mjs --port=30000 --headless --noupdate --dataPath=/data
ENTRYPOINT | ./entrypoint.sh

**Comment by felddy** [comment, marked as answer]
Great question!  
I've answered it [before in other places](https://gist.github.com/felddy/5e737f60559e90041be192d59159ab7c), but I guess not in this repository's discussions.

Here is an example `docker-compose.yml` file that should do what you're trying to accomplish:

```yml
---
version: "3"

secrets:
  credentials:
    file: credentials.json

services:
  foundry_1:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host_1
    init: true
    volumes:
      - type: bind
        source: ./data_1
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - FOUNDRY_LICENSE_KEY=1
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
  foundry_2:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host_2
    init: true
    volumes:
      - type: bind
        source: ./data_2
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - FOUNDRY_LICENSE_KEY=2
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: 30000
        published: 30001
        protocol: tcp
```

See also:
- https://github.com/felddy/foundryvtt-docker/discussions/166
- https://github.com/felddy/foundryvtt-docker/discussions/134
- https://github.com/felddy/foundryvtt-docker/discussions/179
- https://github.com/felddy/foundryvtt-docker/discussions/216
