### DISCUSSION TITLE
Giving my Foundry access to external folder with assets

### DISCUSSION THREAD

**Discussion by Mifgan** [felddy/foundryvtt-docker#392] [Q&A] [answered]
Hi!

I'm experimenting to give my Foundry installation access to an external folder (also hosted on my Synology) so that I shouldn't copy all data to my docker folder like I do now. 

My current folder structure looks like this: 
`/volume1/docker/foundry-live/data/Data`
Within the Data folder there's a Resources folder that currently serves as repository for all kinds of copied data (tokens, maps, tiles and images I refer to in Foundry). 
I want to add:
`/volume1/docker/foundry-live/data/Data/Resources/TTRPG`
Or something similar, as a symlink to my main assets folder situated at: 
`/volume1/Books/E-Books/Hobby/Tabletop RPG's`

I tried to make a symlink (ln -s) to: 
`/volume1/docker/foundry-live/data/Data/Resources/TTRPG`
That works fine within Terminal, but with this docker-compose it doesn't even see the folder. 

```yml
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:9.269
    hostname: ...
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./data
        target: /data
            
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - FOUNDRY_PASSWORD=...
      - FOUNDRY_USERNAME=...
      - FOUNDRY_ADMIN_KEY=...
      - CONTAINER_PRESERVE_CONFIG=true
      - CONTAINER_VERBOSE=false
      - CONTAINER_PRESERVE_OWNER=/data/Data/Resources/TTRPG

    ports:
      - target: "30000"
        published: "..."
        protocol: tcp
        mode: host
```

When I add this extra volume to bind my main assets folder to the TTRPG folder, it becomes visible in Foundry's file explorer, but I can't see the content due to a permission error. I get it both with or without making the manual symlink in Terminal. 
```yml
      - type: bind
        source: /volume1/Books/E-Books/Hobby/Tabletop RPG's
        target: /data/Data/Resources/TTRPG
        read_only: true
```
![image](https://user-images.githubusercontent.com/13572985/182199130-a1bb8105-dc45-4dba-afeb-33bb5cbe9946.png)

I've searched around and found discussions like [153](https://github.com/felddy/foundryvtt-docker/discussions/153) that point to people having solved this vexing conundrum. Maybe someone has a tip on how to solve it?
Thanks in advance!
