### DISCUSSION TITLE
Wrong version of container starting from compose file

### DISCUSSION THREAD

**Discussion by jshank** [felddy/foundryvtt-docker#451] [Q&A] [answered]
### Bug description

When starting the container, I receive the following 
```
[info] Starting felddy/foundryvtt container v10.284.0
[warn] FOUNDRY_VERSION has been manually set and does not match the container's version.
[warn] Expected 10.284 but found 10.285
```

I've upgraded to the latest container but somehow v10.284.0 has been "locked into the image". Looking through the Dockerfile, it declares  `ARG VERSION` which is later sent to a text file. `echo ${VERSION} > image_version.txt`. This doesn't appear to get updated on subsequent updates to the image file. 

### Steps to reproduce

- Download https://github.com/felddy/foundryvtt-docker/blob/develop/docker-compose.yml file
- Modify the docker-compose.yml as follows:
```
    environment:
      - CONTAINER_PRESERVE_CONFIG=true
      - FOUNDRY_VERSION=10.285
```
- Execute docker-compose up -d
- Later upgrade to a newer version of the image

### Expected behavior

Container version matches the release version of foundry

### Container metadata

```shell
com.foundryvtt.version = "10.286"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2022-09-20T21:36:07.057Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "7144434df48d7551e8b64b0664ea597fb0b0d68f"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "10.286.0"
```

### Relevant log output

```console
foundryvtt | Entrypoint | 2022-09-20 20:59:37 | [info] Starting felddy/foundryvtt container v10.284.0
foundryvtt | Entrypoint | 2022-09-20 20:59:37 | [warn] FOUNDRY_VERSION has been manually set and does not match the container's version.
foundryvtt | Entrypoint | 2022-09-20 20:59:37 | [warn] Expected 10.284 but found 10.285
foundryvtt | Entrypoint | 2022-09-20 20:59:37 | [warn] The container may not function properly with this version mismatch.
foundryvtt | Entrypoint | 2022-09-20 20:59:38 | [info] Foundry Virtual Tabletop 10.285 is installed.
foundryvtt | Entrypoint | 2022-09-20 20:59:38 | [info] Not modifying existing installation license key.
foundryvtt | Entrypoint | 2022-09-20 20:59:38 | [info] Setting data directory permissions.
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by felddy** [comment]
Thank you for the report.  

This warning message you are seeing is working as expected.  You have manually set the `FOUNDRY_VERSION` environment variable in your docker compose file.  The version you set does not match the version that was used to create the container.  The container will probably work as expected, but it was not tested in this configuration.  

To correctly update your container remove the `FOUNDRY_VERSION` from your docker compose file, and pull a new image for the version.  For example, if your compose file is using `felddy/foundryvtt:release` you can run `docker compose pull` and then `docker compose up --detach ` 

See:
- https://github.com/felddy/foundryvtt-docker/discussions/208
- https://github.com/felddy/foundryvtt-docker/blob/develop/README.md#updating-your-container

**Comment by jshank** [comment]
I commented out the FOUNDRY_VERSION tag and pulled a new version. The issue persists:

```
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [info] Starting felddy/foundryvtt container v10.284.0
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [warn] FOUNDRY_VERSION has been manually set and does not match the container's version.
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [warn] Expected 10.284 but found 10.286
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [warn] The container may not function properly with this version mismatch.
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [info] Reading configured secrets from: /run/secrets/config.json
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [info] Foundry Virtual Tabletop 10.285 is installed.
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [info] Requested version (10.286) from FOUNDRY_VERSION differs.
foundryvtt | Entrypoint | 2022-09-21 07:54:52 | [info] Uninstalling version 10.285.
```

**Comment by felddy** [comment]
The current version of the container is [`10.286.1`](https://github.com/felddy/foundryvtt-docker/releases/tag/v10.286.1).  Your log is showing container version `10.284.0`.

Verify that the tag you are using in your `docker-compose.yml` file is as expected.  Usually this is `:release`.  

Also check your logs to see if Docker is "recreating" the container.  You'll want to re-`up` it so it is recreated with the image of the container you pulled, and the new environment with `FOUNDRY_VERSION` removed.  

Here is the output I see after changing the image from `felddy/foundryvtt:10.286.0` to `felddy/foundryvtt:release`:

```console
❱ docker compose pull
foundry Pulling 
foundry Pulled 

❱ docker compose up --detach
Container foundryvtt-docker-foundry-1  Recreate
Container foundryvtt-docker-foundry-1  Recreated
Container foundryvtt-docker-foundry-1  Starting
Container foundryvtt-docker-foundry-1  Started
```

**Comment by jshank** [comment]
Confirmed docker-compose is using :release.
I've done docker-compose down (twice for good measure) then docker-compose up.
I've deleted the image completely and redownloaded.

What gets me is that :release is showing `org.opencontainers.image.version = "10.286.1"` but still shows `Starting felddy/foundryvtt container v10.284.0` 

How does `VERSION` get populated in the first place?

**Comment by felddy** [comment]
> How does VERSION get populated in the first place?

`VERSION` is passed in at build time.  If you were to build the container by hand you'd do it [like this](https://github.com/felddy/foundryvtt-docker#building-from-source):

```console
docker build \
  --build-arg VERSION=10.286.1 \
  --tag felddy/foundryvtt:10.286.1 \
  https://github.com/felddy/foundryvtt-docker.git#develop
```

In this repo, the builds are executed by GitHub Actions.   The version of the image lives in `_version.py`  and is read by the workflows:

https://github.com/felddy/foundryvtt-docker/blob/920129381a0e077a75077accd24537a39a6b80cd/src/_version.py#L3

https://github.com/felddy/foundryvtt-docker/blob/920129381a0e077a75077accd24537a39a6b80cd/.github/workflows/_metadata.yml#L49-L52

https://github.com/felddy/foundryvtt-docker/blob/920129381a0e077a75077accd24537a39a6b80cd/.github/workflows/build.yml#L139-L148

I'm know you said you did a `down`.  Just making sure you weren't doing `stop` instead.  They have different semantics.  

What does your docker image list output look like?  

```console
❱ docker images felddy/foundryvtt
REPOSITORY          TAG        IMAGE ID       CREATED        SIZE
felddy/foundryvtt   10.286.1   3f929a6d0949   4 hours ago    221MB
felddy/foundryvtt   release    3f929a6d0949   4 hours ago    221MB
felddy/foundryvtt   10.286.0   166c6f356977   21 hours ago   221MB
felddy/foundryvtt   10.277.0   55dad723c92a   6 weeks ago    211MB
felddy/foundryvtt   10.276.0   2491574f1d76   7 weeks ago    211MB
felddy/foundryvtt   10.265.0   1844a4b8efbd   3 months ago   211MB
```

**Comment by jshank** [comment]
Thanks for sharing how that gets created.
```
docker images felddy/foundryvtt
REPOSITORY          TAG       IMAGE ID       CREATED        SIZE
felddy/foundryvtt   release   3f929a6d0949   5 hours ago    221MB
felddy/foundryvtt   <none>    166c6f356977   22 hours ago   221MB
```

**Comment by felddy** [comment]
Hmmm.  I have no idea!  But I am ready for the exciting conclusion.  Please don't give up on this.
I'm going to covert this into a discussion.

**Reply by felddy** [reply]
Would you be able to post your `docker-compose.yml` file?

**Comment by jshank** [comment, marked as answer]
Happy to share. Let me know if you see any red flags. 
```yml
---
version: "3.8"

secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    container_name: foundryvtt
    image: felddy/foundryvtt:release
    restart: unless-stopped
    hostname: shank_foundry_host
    init: true
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./foundry
        target: /home/foundry
      - type: bind
        source: '/mnt/media/seadrivecli/My Libraries/My Library/D&D'
        target: '/data/Data/D&D'
        read_only: true
      - type: bind
        source: '/mnt/media/music_organized'
        target: '/data/Data/music'
        read_only: true
    environment:
      - CONTAINER_PRESERVE_CONFIG=true
      - CONTAINER_PRESERVE_OWNER=/data/Data/D&D\|/data/Data/music
      - TIMEZONE=America/Los_Angeles
      - FOUNDRY_UID=1000
      - FOUNDRY_VERSION=10.285
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "diun.enable=false"
```

**Reply by felddy** [reply]
Ah ha!  This would be the cause:

```yml 
      - type: bind
        source: ./foundry
        target: /home/foundry
```

The `/home/foundry` path is meant to be ephemeral.  When you start a new version of the container, the updated home directory is getting clobbered by the previously saved one.  Removing this volume will fix the issue you've reported.

See: 
- https://github.com/felddy/foundryvtt-docker#volumes
