### DISCUSSION TITLE
What to do if a new version of FoundryVTT is released but the container hasn't been updated yet.

### DISCUSSION THREAD

**Discussion by felddy** [felddy/foundryvtt-docker#796] [Show and tell]
If you cannot wait for a new version of the container to be released you can manually set the `FOUNDRY_VERSION` environment variable to the version of FoundryVTT you want installed.   For example if you want `11.309` you can set the `FOUNDRY_VERSION` to `11.309` and restart the container.  It will log a warning message about the version mismatch, and then happily install the version you requested.  

For example:

```yaml
 ---
 version: "3.8"

 services:
   foundry:
     image: felddy/foundryvtt:release
     hostname: my_foundry_host
     volumes:
       - type: bind
         source: <your_data_dir>
         target: /data
     environment:
       - FOUNDRY_ADMIN_KEY=atropos
       - FOUNDRY_PASSWORD=N0wN0wNOW
       - FOUNDRY_USERNAME=TheBleedingEdge
       - FOUNDRY_VERSION=11.309
     ports:
       - target: 30000
         published: 30000
         protocol: tcp
 ```
