### DISCUSSION TITLE
Two containers under different subdomains

### DISCUSSION THREAD

**Discussion by tafk7** [felddy/foundryvtt-docker#814] [Q&A]
I'm trying to setup two different docker containers hosted on the same server under different subdomains. I've gotten each container to work on its own, but when trying to run at the same time one of them consistently gives a 502 error. I've been troubleshooting this for a couple days and am rather confounded. Any help would be greatly appreciated.

**docker_compose.yml**
```
---
version: "3.8"

secrets:
  config_json_1:
    file: secrets1.json
  config_json_2:
    file: secrets2.json

services:
  foundry-1:
    image: felddy/foundryvtt:latest
    container_name: foundry-1
    hostname: foundry-1
    volumes:
      - ./fvttdata1:/data
    ports:
      - target: 30000
        published: 30001
        protocol: tcp
    restart: unless-stopped
    environment:
      - FOUNDRY_TELEMETRY=false
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - CONTAINER_VERBOSE=true
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_HOSTNAME=one.example.com
    secrets:
      - source: config_json_1
        target: config.json
    networks:
      - network_1

  foundry-2
    image: felddy/foundryvtt:latest
    container_name: foundry-2
    hostname: foundry-2
    volumes:
      - ./fvttdata2:/data
    ports:
      - target: 30000
        published: 30002
        protocol: tcp
    restart: unless-stopped
    environment:
      - FOUNDRY_TELEMETRY=false
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - CONTAINER_VERBOSE=true
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_HOSTNAME=two.example.com
    secrets:
      - source: config_json_2
        target: config.json
    networks:
      - network_2

  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./nginx:/config
      - /etc/letsencrypt:/config/keys
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    networks:
      - network_1
      - network_2

networks:
  network_1:
    driver: bridge
  network_2:
    driver: bridge
```

**Nginx configs** 

**example1.conf**
```
server {
    # Enter your fully qualified domain name or leave blank
    server_name             one.example.com;

    # Listen on port 443 using SSL certificates
    listen                  443 ssl;
    include                 /config/nginx/ssl-one.conf;

    # Sets the Max Upload size to 300 MB
    client_max_body_size 300M;

    # Proxy Requests to Foundry VTT
    location / {

        # Set proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # These are important to support WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # Make sure to set your Foundry VTT port number
        proxy_pass http://foundry-1:30000;
    }
}

# Optional, but recommend. Redirects all HTTP requests to HTTPS for you
server {
    if ($host = one.example.com) {
        return 301 https://$host$request_uri;
    }
    listen 80;
    listen [::]:80;
    server_name one.example.com;
    return 404;
}
```

**example2.conf**
```
server {
    # Enter your fully qualified domain name or leave blank
    server_name             two.example.com;

    # Listen on port 443 using SSL certificates
    listen                  443 ssl;
    include                 /config/nginx/ssl-2conf;

    # Sets the Max Upload size to 300 MB
    client_max_body_size 300M;

    # Proxy Requests to Foundry VTT
    location / {

        # Set proxy headers
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        # These are important to support WebSockets
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";

        # Make sure to set your Foundry VTT port number
        proxy_pass http://foundry-2:30002;
    }
}

# Optional, but recommend. Redirects all HTTP requests to HTTPS for you
server {
    if ($host = two.example.com) {
        return 301 https://$host$request_uri;
    }

    listen 80;
    listen [::]:80;

    server_name two.example.com;
    return 404;
}
```

I'm running on an Azure VM with the port rules shown in the attached image
![Screenshot 2023-10-15 190658](https://github.com/felddy/foundryvtt-docker/assets/6666644/85f3c844-6993-4f36-91e9-61ce2fbd903b)
