### DISCUSSION TITLE
Unable to authenticate with secrets or environment variables

### DISCUSSION THREAD

**Discussion by ZStrouse** [felddy/foundryvtt-docker#867] [Q&A] [answered]
The container was running without issue as of this morning. A few hours ago, I stopped the container and did a routine reboot on my server. After the reboot, foundry is unable to authenticate my credentials. I did not change anything in my configuration files in that time. I tried following the solutions from the "Credentials getting mangled" and "EAI_AGAIN error" discussions, but neither of the steps in those seemed to help.

I run the container with docker-compose. My compose file is
```
version: "3.8"
secrets:
  foundry_secrets:
    file: /Config/foundryvtt/foundry/secrets_me.json

services:
  foundry:
    image: felddy/foundryvtt:release
    container_name: foundry
    hostname: foundry
    init: true
    restart: "unless-stopped"
    volumes:
      - /srv/disk/Storage/Foundry/me:/data
    environment:
      - CONTAINER_CACHE=/data/cache
      - FOUNDRY_HOSTNAME=removed
      - FOUNDRY_MINIFY_STATIC_FILES=true
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
      - FOUNDRY_UID=1000
      - FOUNDRY_GID=1000
      - TIMEZONE=removed
      - CONTAINER_VERBOSE=true
    expose:
      - 30000
    secrets:
      - source: foundry_secrets
        target: config.json
```

and the secrets file is
```
{
  "foundry_admin_key": "adminkey",
  "foundry_password": "password",
  "foundry_username": "username"
}
```

I also tried removing all the secrets lines and replacing them with directly entering the password and username as environment variables, with the same result. Here are the verbose logs for the situation.
```
foundry  | Entrypoint | 2024-01-05 04:27:07 | [debug] Timezone set to: removed
foundry  | Entrypoint | 2024-01-05 04:27:07 | [info] Starting felddy/foundryvtt container v11.315.0
foundry  | Entrypoint | 2024-01-05 04:27:07 | [debug] CONTAINER_VERBOSE set.  Debug logging enabled.
foundry  | Entrypoint | 2024-01-05 04:27:07 | [debug] Running as: uid=0(root) gid=0(root) groups=0(root),1(bin),2(daemon),3(sys),4(adm),6(disk),10(wheel),11(floppy),20(dialout),26(tape),27(video)
foundry  | Entrypoint | 2024-01-05 04:27:07 | [debug] Environment: CONTAINER_CACHE=/data/cache
foundry  | CONTAINER_VERBOSE=true
foundry  | FOUNDRY_GID=1000
foundry  | FOUNDRY_HOME=/home/foundry
foundry  | FOUNDRY_HOSTNAME=removed
foundry  | FOUNDRY_MINIFY_STATIC_FILES=true
foundry  | FOUNDRY_PROXY_PORT=443
foundry  | FOUNDRY_PROXY_SSL=true
foundry  | FOUNDRY_UID=1000
foundry  | FOUNDRY_VERSION=11.315
foundry  | HOME=/root
foundry  | HOSTNAME=foundry
foundry  | NODE_VERSION=18.18.2
foundry  | PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
foundry  | PWD=/home/foundry
foundry  | SHLVL=1
foundry  | TIMEZONE=removed
foundry  | YARN_VERSION=1.22.19
foundry  | Entrypoint | 2024-01-05 04:27:07 | [info] Reading configured secrets from: /run/secrets/config.json
foundry  | Entrypoint | 2024-01-05 04:27:07 | [info] No Foundry Virtual Tabletop installation detected.
foundry  | Entrypoint | 2024-01-05 04:27:07 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
foundry  | Authenticate | 2024-01-05 04:27:08 | [debug] Saving cookies to: cookiejar.json
foundry  | Authenticate | 2024-01-05 04:27:08 | [info] Requesting CSRF tokens from https://foundryvtt.com
foundry  | Authenticate | 2024-01-05 04:27:08 | [debug] Fetching: https://foundryvtt.com
foundry  | Authenticate | 2024-01-05 04:27:09 | [info] Logging in as: username
foundry  | Authenticate | 2024-01-05 04:27:09 | [debug] Fetching: https://foundryvtt.com/auth/login/
foundry  | Authenticate | 2024-01-05 04:27:09 | [error] Unable to log in as username, verify your credentials...
foundry  | Authenticate | 2024-01-05 04:27:09 | [error] Unable to authenticate: Unable to log in as username, verify your credentials...
```

Per the recommendation in the "Credentials getting mangled" discussion back in July I also opened a shell in the container and tried manually authenticating.
```
docker run --rm --interactive --tty --entrypoint /bin/sh felddy/foundryvtt:release
/home/foundry # ./authenticate.js --log-level=debug username password /tmp/cookiejar.json
```

This also failed, and the output for that attempt was
```
Authenticate | 2024-01-05 11:01:41 | [debug] Saving cookies to: /tmp/cookiejar.json
Authenticate | 2024-01-05 11:01:41 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2024-01-05 11:01:41 | [debug] Fetching: https://foundryvtt.com
Authenticate | 2024-01-05 11:01:41 | [info] Logging in as: username
Authenticate | 2024-01-05 11:01:41 | [debug] Fetching: https://foundryvtt.com/auth/login/
Authenticate | 2024-01-05 11:01:42 | [error] Unable to log in as username, verify your credentials...
Authenticate | 2024-01-05 11:01:42 | [error] Unable to authenticate: Unable to log in as username, verify your credentials...
```

My username has a - in it and my password has a _ but I was under the impression that that shouldn't be an issue when using secrets. Also, it was working without issue for the past several weeks. I don't think it's a network issue either, because when I do nslookup on foundryvtt.com I get a destination IP address instantly.
Been fighting with this for hours and I'm out of ideas. Any help that can be offered would be deeply appreciated.
