### ISSUE TITLE
Issues with traefik reverse proxy and nginx-proxy

### ISSUE THREAD

**Issue by TheLux83** [felddy/foundryvtt-docker#116]
# 💬 Questions and Help

Hey there. I'm trying to make foundryvtt run in my docker environment with nginx-proxy or traefik as reverse proxy (I've tried on two different servers), but it seems that I'm unable to get a valid ssl certificate.
Here are the error messages from both proxies:

**Traefik**
```
traefik    | time="2020-11-27T09:40:39+01:00" level=error msg="Unable to obtain ACME certificate for domains \"sub.domain.tld\": unable to generate a certificate for the domains [sub.domain.tld]: error: one or more domains had a problem:\n[sub.domain.tld] acme: error: 403 :: urn:ietf:params:acme:error:unauthorized :: The key authorization file from the server did not match this challenge \"4mkuOAtxpL7zv4TxQbdpj1oSbybHxb72M546moVM0bI.xIYdb4NK6tj3L953MqLSs6i7yY1p0v43kP5ZBrOOlHU\" != \"error_kas_28\", url: \n" rule="Host(`sub.domain.tld`)" providerName=http.acme routerName=foundryvtt-secure@docker
```

**nginx-proxy**
```
nginx-proxy          | 2020/11/27 15:41:34 [warn] 44#44: no resolver defined to resolve ocsp.int-x3.letsencrypt.org while requesting certificate status, responder: ocsp.int-x3.letsencrypt.org, certificate: "/etc/nginx/certs/sub.domain.tld.crt"
nginx-proxy          | 2020/11/27 15:41:35 [error] 44#44: *4266 no live upstreams while connecting to upstream, client: 149.224.201.106, server: sub.domain.tld, request: "GET / HTTP/2.0", upstream: "http://sub.domain.tld/", host: "sub.domain.tld"
```
Here is my docker-compose file:
```
foundry:
   image: felddy/foundryvtt:release
   container_name: foundryvtt
   init: true
   restart: "unless-stopped"
   volumes:
     - foundry_data:/data
   environment:
     - FOUNDRY_HOSTNAME=sub.domain.tld
     - FOUNDRY_PROXY_SSL=true
     - TIMEZONE=Europe/Berlin
   ports:
     - "30000:30000"
   secrets:
     - source: config_json
       target: config.json
   labels:
     - "traefik.enable=true"
     - "traefik.http.routers.foundryvtt.entrypoints=http"
     - "traefik.http.routers.foundryvtt.rule=Host(`sub.domain.tld`)"
     - "traefik.http.middlewares.foundryvtt-https-redirect.redirectscheme.scheme=https"
     - "traefik.http.routers.foundryvtt.middlewares=foundryvtt-https-redirect"
     - "traefik.http.routers.foundryvtt-secure.entrypoints=https"
     - "traefik.http.routers.foundryvtt-secure.rule=Host(`sub.domain.tld`)"
     - "traefik.http.routers.foundryvtt-secure.tls=true"
     - "traefik.http.routers.foundryvtt-secure.tls.certresolver=http"
     - "traefik.http.routers.foundryvtt-secure.service=foundryvtt"
     - "traefik.http.services.foundryvtt.loadbalancer.server.port=30000"
     - "traefik.docker.network=web"
```

For nginx-proxy erase everything under `label` and insert under `environments`
```
- VIRTUAL_HOST=sub.domain.tld
- LETSENCRYPT_HOST=sub.domain.tld
- LETSENCRYPT_EMAIL=thelux@domain.tld
- VIRTUAL_PORT=30000
```

I'm honest. I don't know what the problem is. For me, it seems that there is something with the container, since every other container on both server are running without any problems. 
Maybe someone can point me in the right direction.

Thanks for your help in advance.
