### ISSUE TITLE
Environment variables not exported from entrypoint to launcher

### ISSUE THREAD

**Issue by xxlbug** [felddy/foundryvtt-docker#1211]
### Bug description

the "foundry_admin_key" in my secrets.json is not used at container startup and consequently i get a "No Admin Access Key has been configured" warning at startup

```console
Launcher | 2025-05-07 07:50:19 | [info] Generating options.json file.
Launcher | 2025-05-07 07:50:19 | [warn] No 'Admin Access Key' has been configured.
Launcher | 2025-05-07 07:50:19 | [info] Starting Foundry Virtual Tabletop.
```

I have an existing foundry docker compose setup that is unchanged for months but had an foundry update to V13.342 today, is there something missing in my migration to V13 like i had to replace `FOUNDRY_UID` and `FOUNDRY_GID` with `user 123:456` ?

The consequence of all this, is an error on startup to configure an admin key and an unsecured foundry open to the public.

### Steps to reproduce

- have secrets.json with this content
```json
{
    "foundry_admin_key": "xxx",
    "foundry_username": "xxx",
    "foundry_password": "xxx"
}
```
- have a compose file with this content
```yaml
---

    #------------------------ xComment ------------------------
    # configure sensitive data with docker secrets
    # - username and password for the foundryvtt.com website to download release versions
    # - admin password for the server
    secrets:
      foundryConfig:
        file: /path/secrets.json
    
    services:
      # virtual tabletop server
      foundry:
        # use release tag to only get stable releases
        image: felddy/foundryvtt:release
        container_name: foundry
        # according to: https://github.com/felddy/foundryvtt-docker/discussions/159
        # benefit: only need to accept new license if terms change, not because of docker randomized hostname
        hostname: foundryVTT
         # needed from V13 forward, see https://github.com/felddy/foundryvtt-docker/discussions/1197
        user: 123:456
        environment:
          - TZ=Europe/London
          - FOUNDRY_TELEMETRY=false
          - CONTAINER_VERBOSE=true
          # cache foundry release zip download
          - CONTAINER_CACHE=/data/foundry_download_cache
          # configure options so foundry can show the correct adress through the reverse proxy
          - FOUNDRY_HOSTNAME=xxx
          - FOUNDRY_PROXY_PORT=443
          - FOUNDRY_PROXY_SSL=true
          # serve smaller files if possible
          - FOUNDRY_MINIFY_STATIC_FILES=true
          # start a world at reboot
          - FOUNDRY_WORLD=kobold-cauldron
        volumes:
          - /path/config:/data/
          # all media content should stay here
          - /path/media:/data/Data/media
        secrets:
          - source: foundryConfig
            target: config.json
        ports:
          - 30000:30000
        restart: unless-stopped
```

### Expected behavior

Use admin key from secrets.json on startup

### Container metadata

```console
com.foundryvtt.version = "13.342"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2025-05-02T22:38:21.913Z"
org.opencontainers.image.description = "An easy-to-deploy containerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "f82ef28794aa0a467a344a5e9a34d78921e3533d"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "13.342.0"
```

### Relevant log output

```console
Entrypoint | 2025-05-07 07:50:07 | [info] Starting felddy/foundryvtt container v13.342.0
Entrypoint | 2025-05-07 07:50:07 | [info] Reading configured secrets from: /run/secrets/config.json
Entrypoint | 2025-05-07 07:50:07 | [info] No Foundry Virtual Tabletop installation detected.
Entrypoint | 2025-05-07 07:50:07 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
Authenticate | 2025-05-07 07:50:08 | [info] Requesting CSRF tokens from https://foundryvtt.com
Authenticate | 2025-05-07 07:50:09 | [info] Logging in as: xxx
Authenticate | 2025-05-07 07:50:10 | [info] Successfully logged in as: xxx
Entrypoint | 2025-05-07 07:50:10 | [info] Using authenticated credentials to fetch release URL.
ReleaseURL | 2025-05-07 07:50:10 | [info] Fetching presigned release URL for build 342...
Entrypoint | 2025-05-07 07:50:11 | [info] Using CONTAINER_CACHE: /data/foundry_download_cache
Entrypoint | 2025-05-07 07:50:11 | [info] Downloading Foundry Virtual Tabletop release.
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
Entrypoint | 2025-05-07 07:50:12 | [info] Installing Foundry Virtual Tabletop 13.342
Entrypoint | 2025-05-07 07:50:17 | [info] Preserving release archive file in cache.
Entrypoint | 2025-05-07 07:50:19 | [info] Not modifying existing installation license key.
Entrypoint | 2025-05-07 07:50:19 | [info] Starting launcher.
Launcher | 2025-05-07 07:50:19 | [info] Generating options.json file.
Launcher | 2025-05-07 07:50:19 | [warn] No 'Admin Access Key' has been configured.
Launcher | 2025-05-07 07:50:19 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2025-05-07 06:50:20 | [info] Running on Node.js - Version 22.15.0
FoundryVTT | 2025-05-07 06:50:20 | [info] Foundry Virtual Tabletop - Version 13 Build 342
FoundryVTT | 2025-05-07 06:50:20 | [info] User Data Directory - "/data"
FoundryVTT | 2025-05-07 06:50:20 | [info] Application Options:
{
  "awsConfig": null,
  "compressSocket": false,
  "compressStatic": true,
  "cssTheme": "dark",
  "fullscreen": false,
  "hostname": "xxx",
  "hotReload": false,
  "language": "en.core",
  "localHostname": null,
  "passwordSalt": null,
  "port": 30000,
  "protocol": null,
  "proxyPort": 443,
  "proxySSL": true,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "updateChannel": "stable",
  "upnp": false,
  "upnpLeaseDuration": null,
  "world": "kobold-cauldron",
  "adminPassword": null,
  "deleteNEDB": false,
  "noBackups": false,
  "serviceConfig": null
}
FoundryVTT | 2025-05-07 06:50:20 | [info] Software license verification succeeded
FoundryVTT | 2025-05-07 06:50:20 | [warn] The requested World "kobold-cauldron" is not available to auto-launch.
FoundryVTT | 2025-05-07 06:50:20 | [info] Server started and listening on port 30000
FoundryVTT | 2025-05-07 06:50:22 | [info] Created client session xxx
Entrypoint | 2025-05-07 07:50:31 | [warn] TERM signal received.  Shutting down server.
FoundryVTT | 2025-05-07 06:50:31 | [info] Shutting down Foundry Virtual Tabletop server
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
