### ISSUE TITLE
Pre-installed builds cannot authenticate with username and password

### ISSUE THREAD

**Issue by danoost** [felddy/foundryvtt-docker#1221]
### Bug description

When using the "Pre-installed distribution builds" option described in the README, username and password cannot be used to fetch the required license key. 

This appears to be an oversight in the src/entrypoint.sh script. The username and password are only used to fetch a license file during the control flow which downloads and installs Foundry. The next conditional executed (line 353 at time of writing) is one which expects the license file to already be present.

### Steps to reproduce

- Set up a compose file with a relevant `build:` section
- Build and run the compose project
- Observe the attached log output, and see that the web UI is stuck behind the "enter license key" page.

Minimal compose file:

```yaml
services:
  foundry:
    build:
      context: https://github.com/felddy/foundryvtt-docker.git#develop
      secrets:
        - foundry_username
        - foundry_password
    env_file:
      - env.secret   # Contains FOUNDRY_USERNAME and FOUNDRY_PASSWORD with the same content as the secrets

secrets:
  foundry_username:
    file: username.secret
  foundry_password:
    file: password.secret
```

### Expected behavior

Authentication proceeds using environment variables, and the license key is fetched.

### Container metadata

```shell
# Note that there are more here as docker compose adds a lot of metadata about my setup, but they're unrelated to this issue.
"com.foundryvtt.version": "13.342"
"org.opencontainers.image.authors": "markf+github@geekpad.com"
"org.opencontainers.image.vendor": "Geekpad"
```

### Relevant log output

```console
Entrypoint | 2025-05-18 05:26:13 | [info] Starting felddy/foundryvtt container v13.342.2
Entrypoint | 2025-05-18 05:26:13 | [info] Foundry Virtual Tabletop 13.342 is installed.
Entrypoint | 2025-05-18 05:26:13 | [info] Installation not yet licensed.
Entrypoint | 2025-05-18 05:26:13 | [warn] Unable to apply a license key since neither a license key nor credentials were provided.  The license key will need to be entered in the browser.
Entrypoint | 2025-05-18 05:26:13 | [info] Starting launcher.
Launcher | 2025-05-18 05:26:13 | [info] Generating options.json file.
Launcher | 2025-05-18 05:26:13 | [info] Setting 'Admin Access Key'.
Launcher | 2025-05-18 05:26:13 | [info] Starting Foundry Virtual Tabletop.
FoundryVTT | 2025-05-18 05:26:13 | [info] Running on Node.js - Version 22.15.1
FoundryVTT | 2025-05-18 05:26:13 | [info] Foundry Virtual Tabletop - Version 13 Build 342
FoundryVTT | 2025-05-18 05:26:13 | [info] User Data Directory - "/data"
FoundryVTT | 2025-05-18 05:26:13 | [info] Application Options:
{
  "awsConfig": null,
  "compressSocket": false,
  "compressStatic": true,
  "cssTheme": "dark",
  "fullscreen": false,
  "hostname": "<snip>",
  "hotReload": false,
  "language": "en.core",
  "localHostname": null,
  "passwordSalt": "<snip>",
  "port": 30000,
  "protocol": null,
  "proxyPort": 443,
  "proxySSL": true,
  "routePrefix": null,
  "sslCert": null,
  "sslKey": null,
  "updateChannel": "stable",
  "upnp": false,
  "upnpLeaseDuration": null,
  "world": null,
  "adminPassword": "••••••••••••••••",
  "deleteNEDB": false,
  "noBackups": false,
  "serviceConfig": null
}
FoundryVTT | 2025-05-18 05:26:13 | [warn] Software license requires signature.
FoundryVTT | 2025-05-18 05:26:13 | [info] Server started and listening on port 30000
```

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by SaschanenDatum** [comment]
Hi, I think I have a similar, if not the same problem: Authentication failed with upgrades to version 13. Username and password are set and valid. Authentication fails with exit code 134. I also copied and added the error text:
```console
Attaching to compose-configs_foundry_1
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [warn] The environment variable "TIMEZONE" is deprecated and will be ignored.
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [info] Starting felddy/foundryvtt container v13.345.0
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [info] No Foundry Virtual Tabletop installation detected.
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
foundry_1  |
foundry_1  |   #  node[23]: std::unique_ptr<long unsigned int> node::WorkerThreadsTaskRunner::DelayedTaskScheduler::Start() at ../src/node_platform.cc:103
foundry_1  |   #  Assertion failed: (0) == (uv_thread_create(t.get(), start_thread, this))
foundry_1  |
foundry_1  | ----- Native stack trace -----
foundry_1  |
foundry_1  |  1: 0xf6ea57 node::Assert(node::AssertionInfo const&) [node]
foundry_1  |  2: 0xffa00a node::WorkerThreadsTaskRunner::WorkerThreadsTaskRunner(int, node::PlatformDebugLogLevel) [node]
foundry_1  |  3: 0xffa110 node::NodePlatform::NodePlatform(int, v8::TracingController*, v8::PageAllocator*) [node]
foundry_1  |  4: 0xf1a8ce  [node]
foundry_1  |  5: 0xf1bd8c node::Start(int, char**) [node]
foundry_1  |  6: 0x7f61ac48a24a  [/lib/x86_64-linux-gnu/libc.so.6]
foundry_1  |  7: 0x7f61ac48a305 __libc_start_main [/lib/x86_64-linux-gnu/libc.so.6]
foundry_1  |  8: 0xe5b47e _start [node]
foundry_1  | ./entrypoint.sh: line 351:    23 Aborted                 (core dumped) ./authenticate.js ${CONTAINER_VERBOSE+--log-level=debug} --user-agent="${node_user_agent}" "${FOUNDRY_USERNAME}" "${FOUNDRY_PASSWORD}" "${cookiejar_file}"
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [warn] Authentication failed with exit code 134.
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [info] Using CONTAINER_CACHE: /data/container_cache
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [error] Unable to install Foundry Virtual Tabletop!
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [error] Either set FOUNDRY_RELEASE_URL.
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [error] Or set FOUNDRY_USERNAME and FOUNDRY_PASSWORD.
foundry_1  | Entrypoint | 2025-06-15 18:41:04 | [error] Or set CONTAINER_CACHE to a directory containing foundryvtt-13.345.zip
```
Here is also my compose config. The system is an ubuntu
```yaml
version: '3.1'

volumes:
  foundry-data:
     driver: local-persist
     driver_opts:
       mountpoint: /docker-container-data/foundry

services:
  foundry:
    image: felddy/foundryvtt:release  #tried multiple versions
    hostname: a host
    restart: "always"
    volumes:
      - foundry-data:/data
    environment:
      - FOUNDRY_PASSWORD=MyWorkingPassword
      - FOUNDRY_USERNAME=AUserThatIsWorking
      - FOUNDRY_ADMIN_KEY=MyAdminPAssword
      - FOUNDRY_LICENSE_KEY=AKEYTHATWORKS
      - TIMEZONE=Europe/Berlin
      - FOUNDRY_PROXY_SSL=true
    ports:
      - 30000:30000
      - 30000:30000/udp
```

It sounds close to this issue, so maybe it could come from the same source. 
Right now I can not upgrade my container (temp url and Container Cache are also failing) and I can not create a new foundry in a new folder.
