### ISSUE TITLE
Node 16 base Alpine image is incompatible with some arm/v7 servers

### ISSUE THREAD

**Issue by vehrka** [felddy/foundryvtt-docker#196]
# 🐛 Bug Report

I use a raspi4 for my Foundry hosting, I have no problems using `felddy/foundryvtt:0.7.9` (I have tried to recrate it after the present bug and had no problem.

But trying a `docker-compose up --build` of the following configuration I get an `Illegal instruction (core dumped)`

```yml
  foundryvtt85:
    image: felddy/foundryvtt:beta
    hostname: vehrka_foundry_85_cheraserver
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /home/perico/share/foundrydata_8_5
        target: /data
      - type: bind
        source: /etc/letsencrypt
        target: /etc/foundryssl
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - CONTAINER_PRESERVE_CONFIG=true
      - FOUNDRY_UID=1001
    ports:
      - target: "30000"
        published: "30000"
        protocol: tcp
    secrets:
      - source: config_json
        target: config.json
```

## To Reproduce

- Do this
  + run `docker-compose up --build foundryvtt85` for the above configuration

## Expected behavior

Expected to work as the 0.7.9 version does.

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:beta
```

Paste the results here:

```console
com.foundryvtt.version = "0.8.5"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2021-05-21T19:43:06Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "6b2080cb273fabff368ac7c862b68cabbc64aea9"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.git"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.8.5"
```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

```console
foundryvtt85_1  | Entrypoint | 7923-11-24 00:40:56 | [debug] Timezone set to: UTC
foundryvtt85_1  | Entrypoint | 7923-11-26 17:32:08 | [info] Starting felddy/foundryvtt container v0.8.5
foundryvtt85_1  | Entrypoint | 7923-12-08 13:58:48 | [debug] CONTAINER_VERBOSE set.  Debug logging enabled.
foundryvtt85_1  | Entrypoint | 7923-09-15 17:15:04 | [info] Reading configured secrets from: /run/secrets/config.json
foundryvtt85_1  | Entrypoint | 7923-10-24 11:57:12 | [info] No Foundry Virtual Tabletop installation detected.
foundryvtt85_1  | Entrypoint | 7923-11-09 01:08:40 | [info] Using FOUNDRY_USERNAME and FOUNDRY_PASSWORD to authenticate.
foundryvtt85_1  |
foundryvtt85_1  |
foundryvtt85_1  | #
foundryvtt85_1  | # Fatal error in , line 0
foundryvtt85_1  | # unreachable code
foundryvtt85_1  | #
foundryvtt85_1  | #
foundryvtt85_1  | #
foundryvtt85_1  | #FailureMessage Object: 0xbef7750c
foundryvtt85_1  | Illegal instruction (core dumped) 
```
