### ISSUE TITLE
Reverse solidus (backslash) in secrets json file causes jq parse errors

### ISSUE THREAD

**Issue by CaosFR** [felddy/foundryvtt-docker#256]
# 🐛 Bug Report

Hi,

I try to use the secret in my docker-compose.yml but I got a error at start.
Maybe it's bad formating at the ligne 3 but after a huge search in dont find my error.
Of course I have test my docker-compose without sercret file. It work well 

Thanks for help

## To Reproduce

My files :
```console
ls -lisa
1442788 4 -rw-r--r--  1 xxx yyy 1303 Nov  8 17:36 docker-compose.yml
1440627 4 -rw-r--r--  1 xxx yyy  150 Nov  7 22:03 secrets.json
```

secrets.json

```json
{
  "foundry_admin_key": "ZZZZ",
  "foundry_password": "ZZZZ",
  "foundry_username": "ZZZZ"
}
```

docker-compose.yml
```yml
cat docker-compose.yml
version: "3.3"

secrets:
  config_json:
    file: secrets.json

services:
  foundry:
    image: felddy/foundryvtt:latest
    container_name: foundry
    init: true
    restart: "unless-stopped"
    networks:
      - proxy
    volumes:
      - type: bind
        source: /home/roleplay/foundrydata
        target: /data
    environment:
      - FOUNDRY_LANGUAGE=fr.fr-core
      - FOUNDRY_PROXY_SSL=true
    secrets:
      - source: config_json
        target: config.json
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.foundryvtt.entrypoints=http"
      - "traefik.http.routers.foundryvtt.rule=Host(`xxx.xx.xx`)"
      - "traefik.http.middlewares.foundryvtt-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.foundryvtt.middlewares=foundryvtt-https-redirect"
      - "traefik.http.routers.foundryvtt-secure.entrypoints=https"
      - "traefik.http.routers.foundryvtt-secure.rule=Host(`xxx.xx.xx`)"
      - "traefik.http.routers.foundryvtt-secure.tls=true"
      - "traefik.http.routers.foundryvtt-secure.tls.certresolver=http"
      - "traefik.http.routers.foundryvtt-secure.service=foundryvtt"
      - "traefik.http.services.foundryvtt.loadbalancer.server.port=30000"
      - "traefik.docker.network=proxy"

networks:
  proxy:
    external: true
```

## Expected behavior

Run the contenair with secret.

## Any helpful log output

Please run this command:

```bash
docker inspect --format='{{range $k, $v := .Config.Labels}}
    {{- printf "%s = \"%s\"\n" $k $v -}} {{end}}' \
    felddy/foundryvtt:latest
```

```console
com.foundryvtt.version = "0.8.9"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2021-08-17T17:23:17Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "38cafe9a4342cb790ea97e944ded2aeca486d8a5"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker.git"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "0.8.9"
```

Run the container with `CONTAINER_VERBOSE` set to `true`,and paste any useful
log output here:

```console
Creating foundry ... done
Attaching to foundry
foundry    | Entrypoint | 2021-11-08 16:50:43 | [info] Starting felddy/foundryvtt container v0.8.9
foundry    | Entrypoint | 2021-11-08 16:50:43 | [info] Reading configured secrets from: /run/secrets/config.json
foundry    | parse error: Invalid escape at line 3, column 54
foundry    | parse error: Invalid escape at line 3, column 54
foundry    | parse error: Invalid escape at line 3, column 54
foundry    | parse error: Invalid escape at line 3, column 54
foundry    | parse error: Invalid escape at line 3, column 54
foundry    | Entrypoint | 2021-11-08 16:50:43 | [info] No Foundry Virtual Tabletop installation detected.
foundry    | Entrypoint | 2021-11-08 16:50:43 | [error] Unable to install Foundry Virtual Tabletop!
foundry    | Entrypoint | 2021-11-08 16:50:43 | [error] Either set set FOUNDRY_RELEASE_URL.
foundry    | Entrypoint | 2021-11-08 16:50:43 | [error] Or set FOUNDRY_USERNAME and FOUNDRY_PASSWORD.
foundry    | Entrypoint | 2021-11-08 16:50:43 | [error] Or set CONTAINER_CACHE to a directory containing foundryvtt-0.8.9.zip
```
