### ISSUE TITLE
V10 (Dev3) Login Screen/Tours does not work with route prefix

### ISSUE THREAD

**Issue by Gensokian** [felddy/foundryvtt-docker#387]
# 🐛 Bug Report

## Problem
Since Foundry V10 Dev3 (Tag: Prerelease) the login screen cannot be accessed anymore

## Thesis
Since V10 Developement Preview 3, foundry has added the new Tours feature, guiding new users through the software.

These "tours" go by the /tours directory which is not taken in account by the redirection enviroment variable "FOUNDRY_ROUTE_PREFIX";

![image](https://user-images.githubusercontent.com/9213561/179960167-a5e5630c-30e0-4a21-835c-fc952c58c505.png)

This makes it impossible to launch foundry (in the future) for the dialogue boxes do not render.

## Reproduction
Set a FOUNDRY_ROUTE_PREFIX inside the docker-compose and try to connect to said url. 

```yml
servicename:
     image: felddy/foundryvtt:prerelease
     init: true
     restart: "unless-stopped"
     volumes:
       - /path/to/shared:/data/Data/shared
       - /path/to/personal/data:/data
       - /path/to/ddb-data:/data/Data/ddb-images
     environment:
       - FOUNDRY_ROUTE_PREFIX=someone
       - CONTAINER_CACHE=/data/container_cache
```
## Note:
This *could* be an issue on the end of foundry. If that would be the case, I report it on FVTT's end

**Comment by felddy** [comment]
I'd be happy to look into it but I haven't played with the "tours" feature yet.  Do you have steps to configure Foundry for a tour that I can test.

**Comment by Gensokian** [comment]
The tours happen as soon, as foundry tries to launch.

```yml
 version: "3"

 services:
###My proxy for adding services
   proxy:
     hostname: [dnd.myhostname.com]
     image: nginx
     ports:
       - 30000:443
     restart: unless-stopped
     volumes:
       # My custom error messages because it's running on a syno nas
       - ./docker_vtt/error/custom_50x.html:/usr/share/nginx/html/custom_50x.html
       - ./docker_vtt/error/custom_404.html:/usr/share/nginx/html/custom_404.html
     depends_on:
       - james
       - prerelease
  #my first instance, running on stable
   james:
     image: felddy/foundryvtt:release
     init: true
     restart: "unless-stopped"
     volumes:
       #A shared folder between instances
       - ./docker_vtt/data_shared:/data/Data/shared
       #Just data
       - ./docker_vtt/data_james:/data
       #Imported files from dnd beyond, also shared
       - ./docker_vtt/data_dndbeyond:/data/Data/ddb-images
     environment:
       #my url directory prefix thingie...  Basically routing me to the instance of [dnd.myhostname.com/james]
       - FOUNDRY_ROUTE_PREFIX=james
       #Caching the downloaded zip files for faster refresh
       - CONTAINER_CACHE=/data/container_cache
       #Login stuff
       - FOUNDRY_PASSWORD=[SOMEPASSWORD]
       - FOUNDRY_USERNAME=[SOMEUSERNAME]
       - FOUNDRY_ADMIN_KEY=[AN ADMIN KEY]
       #These are small patches I wrote, to change the layout of the login screen, optional
       - CONTAINER_PATCH_URLS=https://git.james-things.com/James/DND_Things/raw/branch/main/James%20Things/foundry%20patches/loginmusic.sh https://git.james-things.com/James/DND_Things/raw/branch/main/James%20Things/foundry%20patches/loginpagecss.sh

# My prerelease instance which gets the error
   prerelease:
     # getting the prerelease
     image: felddy/foundryvtt:prerelease
     init: true
     restart: "unless-stopped"
     volumes:
       #A shared folder between instances
       - ./docker_vtt/data_shared:/data/Data/shared
       #Just data
       - ./docker_vtt/data_prerelease:/data
       #Imported files from dnd beyond, also shared
       - ./docker_vtt/data_dndbeyond:/data/Data/ddb-images
     environment:
       #my url directory prefix thingie...  Basically routing me to the instance of [dnd.myhostname.com/prerelease]
       - FOUNDRY_ROUTE_PREFIX=prerelease
       #Caching the downloaded zip files for faster refresh
       - CONTAINER_CACHE=/data/container_cache
       #Login stuff
       - FOUNDRY_PASSWORD=[SOMEPASSWORD]
       - FOUNDRY_USERNAME=[SOMEUSERNAME]
       - FOUNDRY_ADMIN_KEY=[AN ADMIN KEY]
       #These are small patches I wrote, to change the layout of the login screen, optional
       - CONTAINER_PATCH_URLS=https://git.james-things.com/James/DND_Things/raw/branch/main/James%20Things/foundry%20patches/loginmusic.sh https://git.james-things.com/James/DND_Things/raw/branch/main/James%20Things/foundry%20patches/loginpagecss.sh
```

```
server {
    listen 443;

    client_max_body_size 3000000000000M;

    location /james {
        proxy_pass http://james:30000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    location /prerelease {
        proxy_pass http://prerelease:30000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $host;
    }

    error_page 500 502 503 504 /custom_50x.html;
    location = /custom_50x.html {
            root /usr/share/nginx/html;
    }

	error_page 404 /custom_404.html;
    location = /custom_404.html {
            root /usr/share/nginx/html;
    }
}
```

# Logs and further info
## Foundry (console) log:
```log

Foundry VTT | Foundry Commons Framework Loaded
foundry.js:74276
 _______________________________________________________________
 _____ ___  _   _ _   _ ____  ______   __ __     _______ _____ 
|  ___/ _ \| | | | \ | |  _ \|  _ \ \ / / \ \   / |_   _|_   _|
| |_ | | | | | | |  \| | | | | |_) \ V /   \ \ / /  | |   | |  
|  _|| |_| | |_| | |\  | |_| |  _ < | |     \ V /   | |   | |  
|_|   \___/ \___/|_| \_|____/|_| \_\|_|      \_/    |_|   |_|  
===============================================================

foundry.js:74286 Foundry VTT | Reestablishing existing session a281fc8d54469dab914c653e
foundry.js:7169 Foundry VTT | Connected to server socket using session a281fc8d54469dab914c653e
foundry.js:7259 Foundry VTT | Initializing Foundry Virtual Tabletop Game
foundry.js:6305 Foundry VTT | Loaded localization file lang/en.json

/tours/installing-a-system.json:1          Failed to load resource: the server responded with a status of 404 ()
commons.js:10520 Uncaught (in promise) Error
    at fetchWithTimeout (commons.js:10520:13)
    at async Object.fetchJsonWithTimeout (commons.js:10536:20)
    at async SetupTour.fromJSON (foundry.js:3545:18)
    at async Setup.registerTours (setup.js:40:7)
    at async Setup.initialize (foundry.js:7277:5)
```
## Docker Compose Log
```log
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/socket.io/?session=a281fc8d54469dab914c653e&EIO=4&transport=websocket HTTP/1.1" 101 370 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/license HTTP/1.1" 200 1919 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/css/style.css HTTP/1.1" 200 24223 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/fonts/fontawesome/css/all.min.css HTTP/1.1" 200 78094 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/jquery.min.js HTTP/1.1" 200 31001 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/handlebars.min.js HTTP/1.1" 200 24205 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/handlebars-intl.min.js HTTP/1.1" 200 7678 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/earcut-edges/earcut-edges.js HTTP/1.1" 200 6349 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/ui/denim.png HTTP/1.1" 200 35029 "https://dnd.james-things.com/james/css/style.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/fonts/signika/signika-regular.woff2 HTTP/1.1" 200 33180 "https://dnd.james-things.com/james/css/style.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/ui/anvil-bg.png HTTP/1.1" 200 80674 "https://dnd.james-things.com/james/css/style.css" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/setup.js HTTP/1.1" 200 20205 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/particle-emitter.min.js HTTP/1.1" 200 9742 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/pixi-graphics-smooth.umd.min.js HTTP/1.1" 200 15009 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/socket.io.min.js HTTP/1.1" 200 13067 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/clipper/clipper.js HTTP/1.1" 200 45085 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/commons.js HTTP/1.1" 200 88136 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/showdown.js HTTP/1.1" 200 39409 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/pixi.min.js HTTP/1.1" 200 132699 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/handlebars-intl.min.js.map HTTP/1.1" 200 55625 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/prosemirror.js HTTP/1.1" 200 151264 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/tinymce.min.js HTTP/1.1" 200 139802 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/pixi-graphics-smooth.umd.min.js.map HTTP/1.1" 200 9027 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/particle-emitter.min.js.map HTTP/1.1" 200 47761 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:12 +0000] "GET /james/scripts/socket.io.min.js.map HTTP/1.1" 200 39839 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:13 +0000] "GET /james/scripts/showdown.js.map HTTP/1.1" 200 67393 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:13 +0000] "GET /james/scripts/foundry.js HTTP/1.1" 200 547719 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:13 +0000] "GET /james/scripts/pixi.min.js.map HTTP/1.1" 200 319224 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:13 +0000] "GET /james/icons/vtt.png HTTP/1.1" 200 5088 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:13 +0000] "GET /james/lang/en.json HTTP/1.1" 200 27439 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
proxy_1  | 2022/07/20 20:31:13 [error] 26#26: *1500 open() "/etc/nginx/html/tours/installing-a-system.json" failed (2: No such file or directory), client: 172.29.0.1, server: , request: "GET /tours/installing-a-system.json HTTP/1.1", host: "dnd.james-things.com", referrer: "https://dnd.james-things.com/james/license"
proxy_1  | 172.29.0.1 - - [20/Jul/2022:20:31:13 +0000] "GET /tours/installing-a-system.json HTTP/1.1" 404 25235 "https://dnd.james-things.com/james/license" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/102.0.5005.149 Safari/537.36" "85.1.92.200"
```

I think the last two lines seem to be giving it away, that either foundry, or your dockerized instance is not prefixing the "/james/" to the "/tours/..." directory ...
