### ISSUE TITLE
Deprecating save-state and set-output commands in GitHub Actions workflows

### ISSUE THREAD

**Issue by felddy** [felddy/foundryvtt-docker#503]
### Feature description

Remediate usage of `set-output` and `save-state` in GitHub Actions workflows.

### Motivation

See:
- https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

### Example

Examples

A workflow using save-state or set-output like the following

```yml
- name: Save state
  run: echo "::save-state name={name}::{value}"

- name: Set output
  run: echo "::set-output name={name}::{value}"
```

should be updated to write to the new GITHUB_STATE and GITHUB_OUTPUT environment files:

```yml
- name: Save state
  run: echo "{name}={value}" >> $GITHUB_STATE

- name: Set output
  run: echo "{name}={value}" >> $GITHUB_OUTPUT
```

### Pitch

If it isn't fixed by June 1, 2023 badness will ensue. 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
