### ISSUE TITLE
Unable to run server on any port other than default

### ISSUE THREAD

**Issue by kalebr** [felddy/foundryvtt-docker#61]
# 💬 Questions and Help
Running using docker-compose, setting port to something like 30002 in the yaml file and also changing it in options.json file, when restarting the image, it resets back to port 30000.  How would I run an instance using a different port?

    foundry:
        container_name: fvtt
        image: felddy/foundryvtt:release
        restart: "unless-stopped"
        volumes:
          - '/data/docker/foundryvtt:/data'
        environment:
          - FOUNDRY_PASSWORD=password
          - FOUNDRY_USERNAME=user
          - FOUNDRY_ADMIN_KEY=anotherpassword
        ports:
          - "30002:30002/tcp"
        network_mode: host

**Comment by felddy** [comment]
We covered a bit of this on the discord.  Just documenting it here for anyone else that has similar questions.  

This `docker-compose.yml` file will run two Foundry services listening on ports `30001` and `30002`. 

```yml
---
version: "3.8"

secrets:
  credentials:
    file: credentials.json

services:
  foundry_1:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host_1
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./data_1
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - FOUNDRY_LICENSE_KEY=1
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: "30000"
        published: "30001"
        protocol: tcp
        mode: host
  foundry_2:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host_2
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./data_2
        target: /data
    environment:
      - CONTAINER_CACHE=/data/container_cache
      - FOUNDRY_LICENSE_KEY=2
    secrets:
      - source: credentials
        target: config.json
    ports:
      - target: "30000"
        published: "30002"
        protocol: tcp
        mode: host
```

**Comment by kalebr** [comment]
Got it to work by removing the 
`
mode:host
`

**Comment by felddy** [comment]
Glad you got it working!  🎉 

Don't hesitate to me know if you have any other questions about the project.

**Comment by quadur** [comment]
Okay I wan't to launch two instances using docker-compose on one machine using two different accounts. The main problem is that using the ports option seems to be ignored by the generated options.json; i.e. the following config still generates: 

```json
foundry_2_1  |   "port": 30000,
foundry_2_1  |   "upnp": false,
```

```yaml
---
version: "3.8"

services:
  foundry_2:
    image: felddy/foundryvtt:release
    hostname: hostname.com
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: /home/user/data/
        target: /data
    environment:
      - FOUNDRY_USERNAME=user
      - FOUNDRY_PASSWORD=password
      - FOUNDRY_ADMIN_KEY=password2
      - FOUNDRY_PROXY_PORT=443
      - FOUNDRY_PROXY_SSL=true
    ports:
      - target: "35000"
        published: "35000"
        protocol: tcp
```
