### ISSUE TITLE
Build workflow references invalid metadata output `is_latest`

### ISSUE THREAD

**Issue by felddy** [felddy/foundryvtt-docker#694]
### Bug description

The reference to `is_latest` should be `latest`.  

This is preventing the description from being published during a release of a "latest" image.

See:
https://github.com/felddy/foundryvtt-docker/blob/349bc278fa92049dd2b480b322fc30a0842221fb/.github/workflows/build.yml#L244

https://github.com/felddy/reusable-workflows/blob/23d9d7bef326a63063b3d36f68bcf1817b11eb90/.github/workflows/docker-metadata.yml#L22-L24
```yaml
      latest:
        description: "True if the image is the latest version"
        value: ${{ jobs.metadata.outputs.latest }}
 ```

### Steps to reproduce

- Create release
- Mark as "latest"
- Publish
- Note that description does not get published

### Expected behavior

Description is published for latest releases. 

### Container metadata

```shell
NA
```

### Relevant log output

```console
NA
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
