### ISSUE TITLE
Auth Page not loading correctly

### ISSUE THREAD

**Issue by k4rm4c0m4** [felddy/foundryvtt-docker#805]
### Bug description

In case it matters, the whole thing runs behind a reverse proxy, more specifically caddy & is also behind cloudflares proxy servers. Since I am able to access the page and was able to set it up completely once before restarting, I do not think the issue stems from there. I have disabled caching & proxy completely for testing and have not found a noticable improvement.

When (re)starting the container, it redirects to /auth and fails to load the screen entirely and produces two errors in the log.
```
foundry.js:4194 Uncaught SyntaxError: Unexpected identifier '#type' (at foundry.js:4194:69)
setup.js:7 Uncaught ReferenceError: Application is not defined
    at setup.js:7:22
    at setup.js:5696:3
```

From here, you cannot use the application correctly.

For reference, my Docker-Compose is as follows:
```yaml
---
version: "3.8"

services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: https://foundry.domain.tld
    volumes:
      - type: bind
        source: ./data
        target: /data
    environment:
      - PUID=1002
      - PGID=1003
      - TIMEZONE=Europe/Berlin
      - FOUNDRY_PASSWORD=
      - FOUNDRY_USERNAME=
      - FOUNDRY_ADMIN_KEY=karmasecret
      - CONTAINER_VERBOSE=true
    ports:
      - target: 30000
        published: 30000
        protocol: tcp
    restart: unless-stopped
```

Logs do not show anything suspicious. License authentication is reported as working, nothing out of the ordinary.

### Steps to reproduce

- Create a container using a barebones docker-compose, as provided in the docker-compose.yml example in this repository.
- Set up the Server
- Reboot the System (or the container)

### Expected behavior

Make the authentication page load correctly to allow the user to access the UI.

### Container metadata

```shell
com.foundryvtt.version = "11.311"
org.opencontainers.image.authors = "markf+github@geekpad.com"
org.opencontainers.image.created = "2023-09-29T00:03:59.458Z"
org.opencontainers.image.description = "An easy-to-deploy Dockerized Foundry Virtual Tabletop server."
org.opencontainers.image.licenses = "MIT"
org.opencontainers.image.revision = "2fac62dd530713a68bdb4f9650b94600abdb50e3"
org.opencontainers.image.source = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.title = "foundryvtt-docker"
org.opencontainers.image.url = "https://github.com/felddy/foundryvtt-docker"
org.opencontainers.image.vendor = "Geekpad"
org.opencontainers.image.version = "11.311.0"
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
